[package]
name = "undifficulty-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
undifficulty-core = { workspace = true }
bevy = { workspace = true }
