[package]
name = "unnpc-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]

unspatial-core = { path = "../unspatial-core" }
unassets-core = { path = "../unassets-core" }
unfoundation-core = { path = "../unfoundation-core" }
unboard-core = { path = "../unboard-core" }
unevents-core = { path = "../unevents-core" }
untypes-core = { path = "../untypes-core" }
unrender-std = { path = "../unrender-std" }
unplayer-core = { path = "../unplayer-core" }

bevy = { workspace = true }
