[package]
name = "unnpc-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]

unspatial-core = { path = "../unspatial-core" }
unbehavior = { path = "../unbehavior" }
unnpc-core = { path = "../unnpc-core" }
unui-core = { path = "../unui-core" }
unfoundation-core = { path = "../unfoundation-core" }
untypes-core = { path = "../untypes-core" }
unrender-std = { path = "../unrender-std" }
unplayer-core = { path = "../unplayer-core" }
unmapload-core = { path = "../unmapload-core" }

bevy = { workspace = true }
