[package]
name = "uninteraction-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
uninteraction-core = { workspace = true }
unspatial-core = { workspace = true }
untypes-core = { workspace = true }
unboard-core = { workspace = true }
unbehavior = { workspace = true }
unrender-std = { workspace = true }
unaudiospatial-core = { workspace = true }


bevy = { workspace = true }
