[package]
name = "unlocomotion-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
unplayer-core = { workspace = true }
unvitals-core = { workspace = true }
untypes-core = { workspace = true }
unspatial-core = { workspace = true }
unbehavior = { workspace = true }
unnavigation-core = { workspace = true }
unrender-std = { workspace = true }
unreplicon-core = { workspace = true }
unaudiospatial-core = { workspace = true }
undifficulty-core = { workspace = true }
unfog-core = { workspace = true }
ungear-core = { workspace = true }
uninteraction-core = { workspace = true }
unnpc-core = { workspace = true }
unui-core = { workspace = true }
untruck-core = { workspace = true }
