[package]
name = "unmanual-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]

untypes-core = { workspace = true }
unfoundation-core = { workspace = true }
unmanual-core = { workspace = true }
unui-core = { workspace = true }

bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
