[package]
name = "unmanual-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unassets-core = { path = "../unassets-core" }
untypes-core = { path = "../untypes-core" }
unfoundation-core = { path = "../unfoundation-core" }
unmapload-core = { path = "../unmapload-core" }
unevents-core = { path = "../unevents-core" }
undifficulty-core = { path = "../undifficulty-core" }
unmanual-core = { path = "../unmanual-core" }
unui-core = { path = "../unui-core" }

bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
