use bevy::prelude::*;
use enum_iterator::Sequence;
use serde::{Deserialize, Serialize};
use unfoundation_core::types::gear::VisualKey;

/// Unique identifiers for different gear sprites.
///
/// Each variant represents a specific sprite or animation frame for a piece of
/// gear. The values are used to index into the gear spritesheet.
#[derive(Debug, Default, PartialEq, Eq, Clone, Copy, Serialize, Deserialize, Reflect, Sequence)]
pub enum GearSpriteID {
    ThermometerOff = 0,
    ThermometerOn,
    ThermalImagerOff,
    ThermalImagerOn,
    EMFMeterOff = 10,
    EMFMeter0,
    EMFMeter1,
    EMFMeter2,
    EMFMeter3,
    EMFMeter4,
    RecorderOff = 20,
    Recorder1,
    Recorder2,
    Recorder3,
    Recorder4,
    FlashlightOff = 30,
    Flashlight1,
    Flashlight2,
    Flashlight3,
    GeigerOff,
    GeigerOn,
    GeigerTick,
    RedTorchOff = 40,
    RedTorchOn,
    UVTorchOff,
    UVTorchOn,
    Photocam,
    PhotocamFlash1,
    PhotocamFlash2,
    IonMeterOff = 50,
    IonMeter0,
    IonMeter1,
    IonMeter2,
    SpiritBoxOff,
    SpiritBoxScan1,
    SpiritBoxScan2,
    SpiritBoxScan3,
    SpiritBoxAns1,
    SpiritBoxAns2,
    RepelentFlaskEmpty = 60,
    RepelentFlaskFull,
    QuartzStone0 = 65,
    QuartzStone1,
    QuartzStone2,
    QuartzStone3,
    QuartzStone4,
    Salt4 = 75,
    Salt3,
    Salt2,
    Salt1,
    Salt0,
    Compass = 80,
    SageBundle0 = 85,
    SageBundle1,
    SageBundle2,
    SageBundle3,
    SageBundle4,
    EStaticMeter = 90,
    Videocam,
    MotionSensor,
    #[default]
    None,
}

impl GearSpriteID {
    pub fn to_visual_key(&self) -> VisualKey {
        match self {
            GearSpriteID::ThermometerOff => VisualKey::new("gear.thermometer.off"),
            GearSpriteID::ThermometerOn => VisualKey::new("gear.thermometer.on"),
            GearSpriteID::ThermalImagerOff => VisualKey::new("gear.thermalimager.off"),
            GearSpriteID::ThermalImagerOn => VisualKey::new("gear.thermalimager.on"),
            GearSpriteID::EMFMeterOff => VisualKey::new("gear.emfmeter.off"),
            GearSpriteID::EMFMeter0 => VisualKey::new("gear.emfmeter.0"),
            GearSpriteID::EMFMeter1 => VisualKey::new("gear.emfmeter.1"),
            GearSpriteID::EMFMeter2 => VisualKey::new("gear.emfmeter.2"),
            GearSpriteID::EMFMeter3 => VisualKey::new("gear.emfmeter.3"),
            GearSpriteID::EMFMeter4 => VisualKey::new("gear.emfmeter.4"),
            GearSpriteID::RecorderOff => VisualKey::new("gear.recorder.off"),
            GearSpriteID::Recorder1 => VisualKey::new("gear.recorder.1"),
            GearSpriteID::Recorder2 => VisualKey::new("gear.recorder.2"),
            GearSpriteID::Recorder3 => VisualKey::new("gear.recorder.3"),
            GearSpriteID::Recorder4 => VisualKey::new("gear.recorder.4"),
            GearSpriteID::FlashlightOff => VisualKey::new("gear.flashlight.off"),
            GearSpriteID::Flashlight1 => VisualKey::new("gear.flashlight.1"),
            GearSpriteID::Flashlight2 => VisualKey::new("gear.flashlight.2"),
            GearSpriteID::Flashlight3 => VisualKey::new("gear.flashlight.3"),
            GearSpriteID::GeigerOff => VisualKey::new("gear.geiger.off"),
            GearSpriteID::GeigerOn => VisualKey::new("gear.geiger.on"),
            GearSpriteID::GeigerTick => VisualKey::new("gear.geiger.tick"),
            GearSpriteID::RedTorchOff => VisualKey::new("gear.redtorch.off"),
            GearSpriteID::RedTorchOn => VisualKey::new("gear.redtorch.on"),
            GearSpriteID::UVTorchOff => VisualKey::new("gear.uvtorch.off"),
            GearSpriteID::UVTorchOn => VisualKey::new("gear.uvtorch.on"),
            GearSpriteID::Photocam => VisualKey::new("gear.photocam"),
            GearSpriteID::PhotocamFlash1 => VisualKey::new("gear.photocam.flash1"),
            GearSpriteID::PhotocamFlash2 => VisualKey::new("gear.photocam.flash2"),
            GearSpriteID::IonMeterOff => VisualKey::new("gear.ionmeter.off"),
            GearSpriteID::IonMeter0 => VisualKey::new("gear.ionmeter.0"),
            GearSpriteID::IonMeter1 => VisualKey::new("gear.ionmeter.1"),
            GearSpriteID::IonMeter2 => VisualKey::new("gear.ionmeter.2"),
            GearSpriteID::SpiritBoxOff => VisualKey::new("gear.spiritbox.off"),
            GearSpriteID::SpiritBoxScan1 => VisualKey::new("gear.spiritbox.scan1"),
            GearSpriteID::SpiritBoxScan2 => VisualKey::new("gear.spiritbox.scan2"),
            GearSpriteID::SpiritBoxScan3 => VisualKey::new("gear.spiritbox.scan3"),
            GearSpriteID::SpiritBoxAns1 => VisualKey::new("gear.spiritbox.ans1"),
            GearSpriteID::SpiritBoxAns2 => VisualKey::new("gear.spiritbox.ans2"),
            GearSpriteID::RepelentFlaskEmpty => VisualKey::new("gear.repellentflask.empty"),
            GearSpriteID::RepelentFlaskFull => VisualKey::new("gear.repellentflask.full"),
            GearSpriteID::QuartzStone0 => VisualKey::new("gear.quartzstone.0"),
            GearSpriteID::QuartzStone1 => VisualKey::new("gear.quartzstone.1"),
            GearSpriteID::QuartzStone2 => VisualKey::new("gear.quartzstone.2"),
            GearSpriteID::QuartzStone3 => VisualKey::new("gear.quartzstone.3"),
            GearSpriteID::QuartzStone4 => VisualKey::new("gear.quartzstone.4"),
            GearSpriteID::Salt4 => VisualKey::new("gear.salt.4"),
            GearSpriteID::Salt3 => VisualKey::new("gear.salt.3"),
            GearSpriteID::Salt2 => VisualKey::new("gear.salt.2"),
            GearSpriteID::Salt1 => VisualKey::new("gear.salt.1"),
            GearSpriteID::Salt0 => VisualKey::new("gear.salt.0"),
            GearSpriteID::Compass => VisualKey::new("gear.compass"),
            GearSpriteID::SageBundle0 => VisualKey::new("gear.sagebundle.0"),
            GearSpriteID::SageBundle1 => VisualKey::new("gear.sagebundle.1"),
            GearSpriteID::SageBundle2 => VisualKey::new("gear.sagebundle.2"),
            GearSpriteID::SageBundle3 => VisualKey::new("gear.sagebundle.3"),
            GearSpriteID::SageBundle4 => VisualKey::new("gear.sagebundle.4"),
            GearSpriteID::EStaticMeter => VisualKey::new("gear.estaticmeter"),
            GearSpriteID::Videocam => VisualKey::new("gear.videocam"),
            GearSpriteID::MotionSensor => VisualKey::new("gear.motionsensor"),
            GearSpriteID::None => VisualKey::new(VisualKey::NONE),
        }
    }
}
