[package]
name = "untmxmap-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]

unboard-core = { path = "../unboard-core" }
untmxmap-core = { path = "../untmxmap-core" }
unmapload-core = { path = "../unmapload-core" }
untypes-core = { path = "../untypes-core" }
untiled-core = { path = "../untiled-core" }
unrender-std = { path = "../unrender-std" }
unsettings-core = { path = "../unsettings-core" }

bevy = { workspace = true }
bevy-persistent = { workspace = true }
bevy_platform = { workspace = true }
normalize-path = { workspace = true }
tiled = { workspace = true }
