[package]
name = "untmxmap-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]

uncore-board = { path = "../uncore-board" }
uncore-assets = { path = "../uncore-assets" }
uncore-events = { path = "../uncore-events" }
uncore-types = { path = "../uncore-types" }
uncore-resources = { path = "../uncore-resources" }
untiled-core = { path = "../untiled-core" }
unrender-std = { path = "../unrender-std" }

bevy = { workspace = true }
bevy_platform = { workspace = true }
normalize-path = { workspace = true }
tiled = { workspace = true }
