[package]
name = "unnet-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
serde = { workspace = true, features = ["derive"] }
unfoundation-core = { path = "../unfoundation-core" }
unevents-core = { path = "../unevents-core" }
untypes-core = { path = "../untypes-core" }
ungear-core = { path = "../ungear-core" }
ungearitems-core = { path = "../ungearitems-core" }
unghost-core = { path = "../unghost-core" }
