[package]
name = "uninteraction-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bevy = { workspace = true }
unspatial-core = { path = "../unspatial-core" }
unrender = { path = "../unrender" }
uncore-board = { path = "../uncore-board" }
uncore-events = { path = "../uncore-events" }
uncore-resources = { path = "../uncore-resources" }
