[package]
name = "uninteraction-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
unspatial-core = { path = "../unspatial-core" }
unbehavior = { path = "../unbehavior" }
unrender-std = { path = "../unrender-std" }
unevents-core = { path = "../unevents-core" }
untypes-core = { path = "../untypes-core" }
