[package]
name = "uncore-systems"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
uncore-foundation = { path = "../uncore-foundation" }
uncore-events = { path = "../uncore-events" }
uncore-resources = { path = "../uncore-resources" }
unplayer-core = { path = "../unplayer-core" }
unrender = { path = "../unrender" }
unspatial = { path = "../unspatial" }
untags = { path = "../untags" }
unghost-core = { path = "../unghost-core" }
unmetrics = { path = "../unmetrics" }
bevy = { workspace = true }
bevy_platform = { workspace = true }
enum-iterator = { workspace = true }
itertools = { workspace = true }
noise = { workspace = true }
