[package]
name = "uncore-systems"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
uncore-foundation = { path = "../uncore-foundation" }
uncore-board = { path = "../uncore-board" }
uncore-assets = { path = "../uncore-assets" }
uncore-events = { path = "../uncore-events" }
uncore-types = { path = "../uncore-types" }
uncore-resources = { path = "../uncore-resources" }
uncore-components = { path = "../uncore-components" }
bevy = { workspace = true }
bevy_platform = { workspace = true }
serde = { workspace = true }
enum-iterator = { workspace = true }
fastapprox = { workspace = true }
rand = { workspace = true }
tiled = { workspace = true }
anyhow = { workspace = true }
ordered-float = { workspace = true }
itertools = { workspace = true }
ndarray = { workspace = true }
noise = { workspace = true }
unsettings = { path = "../unsettings" }
