[workspace]
members = [
    "crates/tools/ghost_list",
    "crates/tools/ghost_radio",
    "crates/tools/text_to_speech/walkie_voice_generator",
    "crates/uncampaign-plugin",
    "crates/unclassic-mode-plugin",
    "crates/unengine-core",
    "crates/unengine-plugin",
    "crates/unassets-core",
    "crates/unbehavior",
    "crates/unboard-core",
    "crates/unevents-core",
    "crates/unfoundation-core",
    "crates/untypes-core",
    "crates/undifficulty-core",
    "crates/undifficulty-plugin",
    "crates/unfog-plugin",
    "crates/unfog-core",
    "crates/unfps-core",
    "crates/unfps-plugin",
    "crates/ungear-core",
    "crates/ungear-plugin",
    "crates/ungearitems-core",
    "crates/ungearitems-plugin",
    "crates/unghost-plugin",
    "crates/unghost-core",
    "crates/uninteraction-core",
    "crates/uninteraction-plugin",
    "crates/unlight-plugin",
    "crates/unlight-core",
    "crates/unmanual-core",
    "crates/unmanual-plugin",
    "crates/unmapload-plugin",
    "crates/unmapload-core",
    "crates/unmaphub-plugin",
    "crates/unmainmenu-plugin",
    "crates/unmenu-core",
    "crates/unmenu-plugin",
    "crates/unmenusettings-plugin",
    "crates/unmetrics-core",
    "crates/unmetrics-plugin",
    "crates/unmission-plugin",
    "crates/unnavigation-core",
    "crates/unnet-core",
    "crates/unnet-plugin",
    "crates/unnpc-plugin",
    "crates/unnoise-core",
    "crates/unpicking-plugin",
    "crates/unpicking-core",
    "crates/unplayer-plugin",
    "crates/unplayer-core",
    "crates/unprofile-core",
    "crates/unprofile-plugin",
    "crates/unrender-std",
    "crates/unrender-plugin",
    "crates/unsettings-core",
    "crates/unsettings-plugin",
    "crates/unspatial-core",
    "crates/unsummary-core",
    "crates/unsummary-plugin",
    "crates/unsound-core",
    "crates/unsound-plugin",
    "crates/untags-core",
    "crates/unthermal-core",
    "crates/unthermal-plugin",
    "crates/untiled-core",
    "crates/untruck-core",
    "crates/untruck-plugin",
    "crates/untmxmap-plugin",
    "crates/unui-core",
    "crates/unui-plugin",
    "crates/unwalkie-plugin",
    "crates/unwalkie-core",
]
resolver = "3"

[workspace.lints.rust]
unreachable_pub = "warn"

[workspace.package]
version = "0.3.2-dev"
edition = "2024"
description = "2D isometric Game about investigating paranormal hauntings"
repository = "https://github.com/deavid/unhaunter/"
license = "Apache-2.0"
authors = ["David Martínez Martí <deavidsedice@gmail.com>"]
homepage = "https://unhaunter.com"

[workspace.dependencies]
rand = { version = "0.10", default-features = false, features = [
    "alloc",
    "std_rng",
    "thread_rng",
] }
rand_distr = "0.6"
enum-iterator = "2.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ron = "0.12"
image = "0.25"
regex = "1.12"
clap = { version = "4.5", features = ["derive"] }
fastapprox = "0.3"
anyhow = "1.0"
thiserror = "2.0"
ordered-float = { version = "5.1", features = ["serde"] }
hierarchical_pathfinding = "0.5"
walkdir = "2.5"
glob = "0.3"
tiled = { version = "0.15", default-features = false }
wasm-bindgen = "0.2"
normalize-path = "0.2"
itertools = "0.14.0"
csv = "1.4"
dirs = "6.0"
strum = { version = "0.27", features = ["derive"] }
noise = { version = "0.9.0", features = ["std"] }
bevy = { version = "0.18", features = ["jpeg", "serialize", "debug"] }
bevy_asset_loader = { version = "0.25.0", features = ["2d"] }
bevy_math = "0.18"
bevy-persistent = { version = "0.10", features = ["all"] }
bevy_platform = "0.18"
bevy_dylib = "0.18"
bevy_picking = "0.18"
ndarray = "0.17"
sha2 = "0.10"
rayon = "1.11"
crossbeam-channel = "0.5"
uuid = { version = "1.13", features = ["v4", "serde"] }

# winit is not for WASM, and needs to be in sync with bevy version
winit = "0.30"

[package]
name = "unhaunter"
default-run = "unhaunter_game"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
wasm-bindgen = { workspace = true }
bevy = { workspace = true }

untypes-core = { path = "crates/untypes-core" }
unassets-core = { path = "crates/unassets-core" }

uncampaign-plugin = { path = "crates/uncampaign-plugin" }
unclassic-mode-plugin = { path = "crates/unclassic-mode-plugin" }
unengine-plugin = { path = "crates/unengine-plugin" }
unfog-plugin = { path = "crates/unfog-plugin" }
unfps-plugin = { path = "crates/unfps-plugin" }
ungear-plugin = { path = "crates/ungear-plugin" }
ungearitems-plugin = { path = "crates/ungearitems-plugin" }
unghost-plugin = { path = "crates/unghost-plugin" }
unlight-plugin = { path = "crates/unlight-plugin" }
unmapload-plugin = { path = "crates/unmapload-plugin" }
unmaphub-plugin = { path = "crates/unmaphub-plugin" }
unmainmenu-plugin = { path = "crates/unmainmenu-plugin" }
unmenu-plugin = { path = "crates/unmenu-plugin" }
unmenusettings-plugin = { path = "crates/unmenusettings-plugin" }
unmetrics-plugin = { path = "crates/unmetrics-plugin" }
unmission-plugin = { path = "crates/unmission-plugin" }
unnet-plugin = { path = "crates/unnet-plugin" }
unnpc-plugin = { path = "crates/unnpc-plugin" }
unplayer-plugin = { path = "crates/unplayer-plugin" }
unprofile-plugin = { path = "crates/unprofile-plugin" }
unsettings-plugin = { path = "crates/unsettings-plugin" }
unsummary-plugin = { path = "crates/unsummary-plugin" }
unthermal-plugin = { path = "crates/unthermal-plugin" }
unsound-plugin = { path = "crates/unsound-plugin" }
unrender-plugin = { path = "crates/unrender-plugin" }
unmanual-plugin = { path = "crates/unmanual-plugin" }
unpicking-plugin = { path = "crates/unpicking-plugin" }
untruck-plugin = { path = "crates/untruck-plugin" }
unwalkie-plugin = { path = "crates/unwalkie-plugin" }
untmxmap-plugin = { path = "crates/untmxmap-plugin" }
unui-plugin = { path = "crates/unui-plugin" }
undifficulty-plugin = { path = "crates/undifficulty-plugin" }
uninteraction-plugin = { path = "crates/uninteraction-plugin" }

[[bin]]
name = "unhaunter_game"
path = "unhaunter/src/bin/unhaunter.rs"

[lib]
crate-type = ["cdylib", "rlib"]
path = "unhaunter/src/lib.rs"

[profile.dev]
opt-level = "s"
lto = false
debug-assertions = true
overflow-checks = true

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = "s"
debug = false
strip = "debuginfo"
codegen-units = 1

debug-assertions = true
overflow-checks = true

# These optimizations for release are trying to target mostly WASM
[profile.release]
opt-level = "s"
# TODO: When WASM gets its own release profile we will keep some debug info to do profiling as well on release.
debug = false
strip = "debuginfo"
# --
debug-assertions = false
overflow-checks = false
lto = "thin"
codegen-units = 1

# TODO: wasm-pack v0.13.2 or v0.14.0 is going to implement custom profiles with --profile $PROFILE.
# This will allow us to have a custom profile for WASM builds, and then make it much more aggressive.

[profile.release.package."*"]
opt-level = "s"
debug = false
strip = "debuginfo"
debug-assertions = false
overflow-checks = false
codegen-units = 1
