# The URL the site will be built for
base_url = "https://www.unhaunter.com"


# The site title and description; used in feeds by default.
title = "Unhaunter Official Website"
description = """Step into the boots of a paranormal investigator in Unhaunter, a 2D isometric ghost hunting game. 
Explore atmospheric haunted locations, mastering specialized equipment like the EMF Meter, Thermometer, UV Torch, and Spirit Box. 
Uncover 8 distinct evidence types—from Freezing Temperatures to RL Presence—to identify the ghost. 
Match the evidence you've gathered against over 44 unique ghost profiles to identify the ghost in a tense deductive challenge.
Navigate vision-obscuring Miasma, and learn to interpret crucial sound cues. 
Manage your sanity and health, survive terrifying ghost hunts by hiding, and finally, craft the specific repellent needed to banish the 
restless spirit. Can you solve the mystery and cleanse the location?
"""

# The default site author.
author = "deavidsedice"

# The default language; used in feeds.
default_language = "en"

# When set to "true", a feed is automatically generated.
generate_feeds = true

# The filenames to use for the feeds. Used as the template filenames, too.
# Defaults to ["atom.xml"], which has a built-in template that renders an Atom 1.0 feed.
# There is also a built-in template "rss.xml" that renders an RSS 2.0 feed.
feed_filenames = ["atom.xml"]

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = [{ name = "tags", rss = true, paginate_by = 5 }]


# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

#theme = "custom"
theme = "custom"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# A list of directories used to search for additional `.sublime-syntax` and `.tmTheme` files.
extra_syntaxes_and_themes = []

# The theme to use for code highlighting.
highlight_theme = "base16-ocean-dark"

[extra]
# Put all your custom variables here

# The URL of social image.
social_image = "icons/unhaunter-logo.png"

# Primary colors
#[extra.style]
#bg_dark_color = "red"


# The profile on home page.
[extra.profile]
name = "Unhaunter"
bio = """Step into the boots of a paranormal investigator in Unhaunter, a 2D isometric ghost hunting game. 
Explore atmospheric haunted locations, mastering specialized equipment like the EMF Meter, Thermometer, UV Torch, and Spirit Box. 
Uncover 8 distinct evidence types—from Freezing Temperatures to RL Presence—to identify the ghost. 
Match the evidence you've gathered against over 44 unique ghost profiles to identify the ghost in a tense deductive challenge.
Navigate vision-obscuring Miasma, and learn to interpret crucial sound cues. 
Manage your sanity and health, survive terrifying ghost hunts by hiding, and finally, craft the specific repellent needed to banish the 
restless spirit. Can you solve the mystery and cleanse the location?
"""

# The URL of avatar.
avatar_url = "icons/unhaunter-logo.png"
title_url = "images/title.svg"

[[extra.profile.social]]
name = "github"
url = "https://github.com/deavid/unhaunter"

[[extra.profile.social]]
name = "reddit"
url = "https://www.reddit.com/r/Unhaunter/"

[[extra.profile.social]]
name = "rss"
url = "$BASE_URL/atom.xml"

# The top menu.
[[extra.menu]]
name = "News"
url = "$BASE_URL/news"

[[extra.menu]]
name = "Blog"
url = "$BASE_URL/blog"

#[[extra.menu]]
#name = "Play in Browser"
#url = "$BASE_URL/wasm/main/"
#new_window = true

[[extra.menu]]
name = "Beta"
url = "$BASE_URL/beta"

[[extra.footer.links]]
name = "matrix"
url = "https://matrix.to/#/#unhaunter:matrix.org"
icon = "icons/matrix.svg"

[[extra.footer.links]]
name = "youtube"
url = "https://www.youtube.com/c/DavidMart%C3%ADnezMart%C3%AD"
icon = "icons/youtube.svg"

[[extra.footer.links]]
name = "reddit"
url = "https://www.reddit.com/r/Unhaunter/"
icon = "icons/reddit.svg"

[[extra.footer.links]]
name = "mastodon"
url = "https://techhub.social/@deavid"
icon = "icons/mastodon.svg"

[[extra.footer.links]]
name = "portfolio"
url = "https://deavid.wordpress.com/"
icon = "icons/portfolio.svg"

[[extra.footer.links]]
name = "github"
url = "https://github.com/deavid/unhaunter"
icon = "icons/github.svg"

# The page footer options.
[extra.footer]
since = 2023
license = "Apache-2.0 License"
license_url = "https://www.apache.org/licenses/LICENSE-2.0"
