[package]
name = "unfog-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]

unspatial-core = { path = "../unspatial-core" }
unbehavior = { path = "../unbehavior" }
unfoundation-core = { path = "../unfoundation-core" }
unboard-core = { path = "../unboard-core" }
unmapload-core = { path = "../unmapload-core" }
unghost-core = { path = "../unghost-core" }
untypes-core = { path = "../untypes-core" }
unrender-std = { path = "../unrender-std" }
unplayer-core = { path = "../unplayer-core" }
unmetrics-core = { path = "../unmetrics-core" }
unnoise-core = { path = "../unnoise-core" }
unfog-core = { path = "../unfog-core" }
unsettings-core = { path = "../unsettings-core" }

bevy = { workspace = true }
bevy-persistent = { workspace = true }
bevy_platform = { workspace = true }
rand = { workspace = true }
ndarray = { workspace = true }
