[package]
name = "unfog-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]

uncommon-states-core = { workspace = true }
unspatial-core = { workspace = true }
unlight-core = { workspace = true }
unbehavior-core = { workspace = true }
unmission-core = { workspace = true }
uncommon-app-core = { workspace = true }
unboard-core = { workspace = true }
unghost-core = { workspace = true }
unrender-std = { workspace = true }
unplayer-core = { workspace = true }
unmetrics-core = { workspace = true }
unnoise-core = { workspace = true }
unfog-core = { workspace = true }
unsettings-core = { workspace = true }
unreplicon-core = { workspace = true }

bevy = { workspace = true }
bevy_replicon = { workspace = true }
bevy-persistent = { workspace = true }
bevy_platform = { workspace = true }
rand = { workspace = true }
ndarray = { workspace = true }
