[package]
name = "unaudiobg-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unaudiobg-core = { path = "../unaudiobg-core" }
unsettings-core = { path = "../unsettings-core" }
unplayer-core = { path = "../unplayer-core" }
unboard-core = { path = "../unboard-core" }
unspatial-core = { path = "../unspatial-core" }
untypes-core = { path = "../untypes-core" }

bevy = { workspace = true }
bevy-persistent = { workspace = true }
ndarray = { workspace = true }
