[package]
name = "unplayer-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
uncore-foundation = { path = "../uncore-foundation" }
unsettings = { path = "../unsettings" }
unspatial-core = { path = "../unspatial-core" }
bevy = { workspace = true }
serde = { workspace = true }
