[package]
name = "unplayer-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unsettings-core = { path = "../unsettings-core" }
unspatial-core = { path = "../unspatial-core" }
ungear-core = { path = "../ungear-core" }
ungearitems-core = { path = "../ungearitems-core" }
unreplicon-core = { workspace = true }
bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
serde = { workspace = true }
