[package]
name = "unlobby-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
enum-iterator = { workspace = true }
unfoundation-core = { workspace = true }
unui-core = { workspace = true }
untypes-core = { workspace = true }
untmxmap-core = { workspace = true }
unmenu-core = { workspace = true }
unreplicon-core = { workspace = true }
unmapload-core = { workspace = true }
undifficulty-core = { workspace = true }
unprofile-core = { workspace = true }
unrender-std = { workspace = true }
bevy-persistent = { workspace = true }
