[package]
name = "unlobby-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
enum-iterator = { workspace = true }
unfoundation-core = { path = "../unfoundation-core" }
unui-core = { path = "../unui-core" }
untypes-core = { path = "../untypes-core" }
untmxmap-core = { path = "../untmxmap-core" }
unmenu-core = { path = "../unmenu-core" }
unreplicon-core = { workspace = true }
unmapload-core = { path = "../unmapload-core" }
undifficulty-core = { path = "../undifficulty-core" }
unprofile-core = { path = "../unprofile-core" }
unrender-std = { path = "../unrender-std" }
bevy-persistent = { workspace = true }
