[package]
name = "ungearitems-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]

unspatial-core = { path = "../unspatial-core" }
unbehavior = { path = "../unbehavior" }
undifficulty-core = { path = "../undifficulty-core" }
unfoundation-core = { path = "../unfoundation-core" }
unboard-core = { path = "../unboard-core" }
unlight-core = { path = "../unlight-core" }
unrender-std = { path = "../unrender-std" }
uninteraction-core = { path = "../uninteraction-core" }
unmetrics-core = { path = "../unmetrics-core" }
ungear-core = { path = "../ungear-core" }
untags-core = { path = "../untags-core" }
unghost-core = { path = "../unghost-core" }
unplayer-core = { path = "../unplayer-core" }
unfog-core = { path = "../unfog-core" }
unsound-core = { path = "../unsound-core" }
unsummary-core = { path = "../unsummary-core" }
unthermal-core = { path = "../unthermal-core" }
unprofile-core = { path = "../unprofile-core" }

bevy = { workspace = true }
bevy-persistent = { workspace = true }
bevy_platform = { workspace = true }
rand = { workspace = true }
ndarray = { workspace = true }
enum-iterator = { workspace = true }
fastapprox = { workspace = true }
ungearitems-core = { path = "../ungearitems-core" }
