[package]
name = "ungearitems-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]

unspatial-core = { workspace = true }
unbehavior-core = { workspace = true }
undifficulty-core = { workspace = true }
uncommon-app-core = { workspace = true }
unboard-core = { workspace = true }
unlight-core = { workspace = true }
unrender-std = { workspace = true }
uninteraction-core = { workspace = true }
unmetrics-core = { workspace = true }
ungear-core = { workspace = true }
unghost-core = { workspace = true }
uninvestigation-core = { workspace = true }
unfog-core = { workspace = true }
unaudiospatial-core = { workspace = true }
unsoundfield-core = { workspace = true }
unthermal-core = { workspace = true }
unprofile-core = { workspace = true }

uncommon-states-core = { workspace = true }
unreplicon-core = { workspace = true }
bevy = { workspace = true }
bevy-persistent = { workspace = true }
bevy_replicon = { workspace = true }
rand = { workspace = true }
ndarray = { workspace = true }
ungearitems-core = { workspace = true }
