[package]
name = "unrender-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }

unbehavior = { path = "../unbehavior" }
unrender-std = { path = "../unrender-std" }
unfoundation-core = { path = "../unfoundation-core" }
untypes-core = { path = "../untypes-core" }
unspatial-core = { path = "../unspatial-core" }
unboard-core = { path = "../unboard-core" }
unmetrics-core = { path = "../unmetrics-core" }
untruck-core = { path = "../untruck-core" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
winit = { workspace = true }
image = { workspace = true }
