[package]
name = "unrender-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }

unrender-std = { workspace = true }
unlocomotion-core = { workspace = true }
unorchestrator-core = { workspace = true }
uncommon-app-core = { workspace = true }
unspatial-core = { workspace = true }
unmetrics-core = { workspace = true }
untruck-core = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
winit = { workspace = true }
image = { workspace = true }
