[package]
name = "unrender-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }

unbehavior = { path = "../unbehavior" }
unrender-std = { path = "../unrender-std" }
untypes-core = { path = "../untypes-core" }
unspatial-core = { path = "../unspatial-core" }
unboard-core = { path = "../unboard-core" }
unplayer-core = { path = "../unplayer-core" }
unmetrics-core = { path = "../unmetrics-core" }
untags-core = { path = "../untags-core" }
