[package]
name = "untruck-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
uncommon-states-core = { workspace = true }
untruck-core = { workspace = true }
uninput-core = { workspace = true }
undifficulty-core = { workspace = true }
unmission-core = { workspace = true }
unreplicon-core = { workspace = true }
unplayer-core = { workspace = true }
unbehavior-core = { workspace = true }
ungear-core = { workspace = true }
ungearitems-core = { workspace = true }
unsettings-core = { workspace = true }
uninvestigation-core = { workspace = true }
unmapload-core = { workspace = true }

bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
bevy-persistent = { workspace = true }
