[package]
name = "untruck-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
untruck-core = { path = "../untruck-core" }
undifficulty-core = { path = "../undifficulty-core" }
unfoundation-core = { path = "../unfoundation-core" }
unevents-core = { path = "../unevents-core" }
untypes-core = { path = "../untypes-core" }
unui-core = { path = "../unui-core" }
unplayer-core = { path = "../unplayer-core" }
unrender-std = { path = "../unrender-std" }
ungear-core = { path = "../ungear-core" }
ungearitems-core = { path = "../ungearitems-core" }
unsettings-core = { path = "../unsettings-core" }
unprofile-core = { path = "../unprofile-core" }
unwalkie-core = { path = "../unwalkie-core" }
unghost-core = { path = "../unghost-core" }
unbehavior = { path = "../unbehavior" }
unnet-core = { path = "../unnet-core" }
unboard-core = { path = "../unboard-core" }

bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
bevy_platform = { workspace = true }
bevy-persistent = { workspace = true }
