[package]
name = "unmapload-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]

unspatial-core = { path = "../unspatial-core" }
unassets-core = { path = "../unassets-core" }
undifficulty-core = { path = "../undifficulty-core" }
unfoundation-core = { path = "../unfoundation-core" }
unboard-core = { path = "../unboard-core" }
unlight-plugin = { path = "../unlight-plugin" }
unevents-core = { path = "../unevents-core" }
untypes-core = { path = "../untypes-core" }
untiled-core = { path = "../untiled-core" }
unnavigation-core = { path = "../unnavigation-core" }
unsummary-core = { path = "../unsummary-core" }
ungear-core = { path = "../ungear-core" }
unsettings-core = { path = "../unsettings-core" }
untags-core = { path = "../untags-core" }
unplayer-core = { path = "../unplayer-core" }
unrender-std = { path = "../unrender-std" }
unghost-core = { path = "../unghost-core" }

bevy = { workspace = true }
bevy-persistent = { workspace = true }
bevy_platform = { workspace = true }
rand = { workspace = true }
ordered-float = { workspace = true }
ndarray = { workspace = true }
