[package]
name = "unmapload-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
bevy_replicon = { workspace = true }
unspatial-core = { workspace = true }
unbehavior = { workspace = true }
unbehavior-core = { workspace = true }
undifficulty-core = { workspace = true }
unboard-core = { workspace = true }
untypes-core = { workspace = true }
untiled-core = { workspace = true }
unrender-std = { workspace = true }
unmetrics-core = { workspace = true }
untmxmap-core = { workspace = true }
unmapload-core = { workspace = true }
unmission-core = { workspace = true }
uninteraction-core = { workspace = true }

bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
bevy_platform = { workspace = true }
ndarray = { workspace = true }
