[package]
name = "unmapload-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[dependencies]

unspatial-core = { path = "../unspatial-core" }
uncore-assets = { path = "../uncore-assets" }
undifficulty = { path = "../undifficulty" }
uncore-foundation = { path = "../uncore-foundation" }
uncore-board = { path = "../uncore-board" }
uncore-events = { path = "../uncore-events" }
uncore-types = { path = "../uncore-types" }
uncore-resources = { path = "../uncore-resources" }
untiled = { path = "../untiled" }
unnavigation-core = { path = "../unnavigation-core" }
unlight-plugin = { path = "../unlight-plugin" }
ungear = { path = "../ungear" }
ungearitems = { path = "../ungearitems" }
unsettings = { path = "../unsettings" }
untags-core = { path = "../untags-core" }
unplayer = { path = "../unplayer" }
unrender = { path = "../unrender" }
unghost = { path = "../unghost" }
unghost-core = { path = "../unghost-core" }

bevy = { workspace = true }
bevy-persistent = { workspace = true }
bevy_platform = { workspace = true }
rand = { workspace = true }
ordered-float = { workspace = true }
ndarray = { workspace = true }
