[package]
name = "unspatial-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bevy = { version = "0.17", features = ["serialize"] }
bevy_math = "0.17"
serde = { version = "1.0", features = ["derive"] }
fastapprox = "0.3"
