[package]
name = "uncore-resources"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
uncore-foundation = { path = "../uncore-foundation" }
uncore-board = { path = "../uncore-board" }
uncore-types = { path = "../uncore-types" }
uncore-events = { path = "../uncore-events" }
uncore-assets = { path = "../uncore-assets" }
unspatial-core = { path = "../unspatial-core" }
unsettings = { path = "../unsettings" }
undifficulty-core = { path = "../undifficulty-core" }
bevy = { workspace = true }
bevy_platform = { workspace = true }
ndarray = { workspace = true }
enum-iterator = { workspace = true }
