[package]
name = "unmenu"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
uncore = { path = "../uncore" }
unsettings = { path = "../unsettings" }
uncoremenu = { path = "../uncoremenu" }
unprofile = { path = "../unprofile" }

bevy = { workspace = true }
bevy_kira_audio = { workspace = true }
bevy-persistent = { workspace = true }
enum-iterator = { workspace = true }
anyhow.workspace = true
serde.workspace = true
