[package]
name = "unlight-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]

unspatial-core = { path = "../unspatial-core" }
unlight-core = { path = "../unlight-core" }
unbehavior = { path = "../unbehavior" }
undifficulty-core = { path = "../undifficulty-core" }
unfoundation-core = { path = "../unfoundation-core" }
unboard-core = { path = "../unboard-core" }
unevents-core = { path = "../unevents-core" }
untypes-core = { path = "../untypes-core" }
unrender-std = { path = "../unrender-std" }
unplayer-core = { path = "../unplayer-core" }
unmetrics-core = { path = "../unmetrics-core" }
uninteraction-core = { path = "../uninteraction-core" }
unui-core = { path = "../unui-core" }
unfog-core = { path = "../unfog-core" }
ungear-core = { path = "../ungear-core" }
ungearitems-core = { path = "../ungearitems-core" }
unsettings-core = { path = "../unsettings-core" }

bevy = { workspace = true }
bevy_platform = { workspace = true }
rand = { workspace = true }
ndarray = { workspace = true }
fastapprox = { workspace = true }
bevy-persistent = { workspace = true }
