[package]
name = "unlight-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]

unspatial-core = { workspace = true }
unlight-core = { workspace = true }
unbehavior-core = { workspace = true }
undifficulty-core = { workspace = true }
unfoundation-core = { workspace = true }
unboard-core = { workspace = true }
unmission-core = { workspace = true }
untypes-core = { workspace = true }
unrender-std = { workspace = true }
unplayer-core = { workspace = true }
unmetrics-core = { workspace = true }
uninteraction-core = { workspace = true }
unui-core = { workspace = true }
unfog-core = { workspace = true }
unreplicon-core = { workspace = true }
ungear-core = { workspace = true }
ungearitems-core = { workspace = true }
unsettings-core = { workspace = true }

bevy = { workspace = true }
bevy_platform = { workspace = true }
rand = { workspace = true }
ndarray = { workspace = true }
fastapprox = { workspace = true }
bevy-persistent = { workspace = true }
