# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "ungame-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]

unspatial-core = { path = "../unspatial-core" }
uncore-assets = { path = "../uncore-assets" }
undifficulty = { path = "../undifficulty" }
uncore-foundation = { path = "../uncore-foundation" }
uncore-board = { path = "../uncore-board" }
uncore-events = { path = "../uncore-events" }
uncore-types = { path = "../uncore-types" }
uncore-resources = { path = "../uncore-resources" }
unui-core = { path = "../unui-core" }
untags-core = { path = "../untags-core" }
unrender = { path = "../unrender" }
unplayer-core = { path = "../unplayer-core" }
unpicking-core = { path = "../unpicking-core" }
uninteraction-core = { path = "../uninteraction-core" }
ungear = { path = "../ungear" }
unsettings = { path = "../unsettings" }
unlight-plugin = { path = "../unlight-plugin" }
unprofile = { path = "../unprofile" }
unplayer = { path = "../unplayer" }
unghost = { path = "../unghost" }
unghost-core = { path = "../unghost-core" }
uncore-components = { path = "../uncore-components" }

bevy = { workspace = true }
bevy_platform = { workspace = true }
bevy-persistent = { workspace = true }
