# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "unclassic-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]

unspatial-core = { path = "../unspatial-core" }
unboard-core = { path = "../unboard-core" }
untypes-core = { path = "../untypes-core" }
untags-core = { path = "../untags-core" }
unrender-std = { path = "../unrender-std" }
unplayer-core = { path = "../unplayer-core" }
unpicking-core = { path = "../unpicking-core" }
unsettings-core = { path = "../unsettings-core" }

bevy = { workspace = true }
bevy-persistent = { workspace = true }
