use bevy::prelude::*;
use serde::{Deserialize, Serialize};
use ungear_core::types::gear::kind::GearKind;

/// Sent by the (room-owner) client to request a map change.
///
/// On the server this arrives as `FromClient<RequestSelectMap>`.
/// The server validates ownership then updates `LobbyInfo.selected_map`.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct RequestSelectMap {
    pub map_filepath: String,
}

/// Sent by the (room-owner) client to request a difficulty change.
///
/// On the server this arrives as `FromClient<RequestSelectDifficulty>`.
/// The server validates ownership then updates `LobbyInfo.selected_difficulty`.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct RequestSelectDifficulty {
    pub difficulty_id: String,
}

/// Sent by the (room-owner) client to start the mission.
///
/// `map_seed` is generated by the sender so all peers use the same value.
/// On the server this arrives as `FromClient<RequestStartMission>`.
/// The server spawns a `(Replicated, SelectedMission)` entity which clients
/// observe to trigger level loading.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct RequestStartMission {
    pub map_seed: u64,
}

/// Sent by a client to request entering the currently running mission.
///
/// On the server this arrives as `FromClient<RequestJoinMission>`.
/// The server validates the sender against `LobbyInfo`, records the player's
/// mission intent, and spawns the player's avatar skeleton once mission
/// spawning is active.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct RequestJoinMission;

/// Explicit reason for requesting that the authority conclude the current mission.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum MissionEndReason {
    TruckExitInitiated,
    LeaderAborted,
}

/// Sent by a client to request that the authority conclude the current mission.
///
/// On the server this arrives as `FromClient<RequestEndMission>`.
/// The authority validates the request based on the reason, then triggers the
/// authority-owned mission teardown flow.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct RequestEndMission {
    pub reason: MissionEndReason,
}

// ---------------------------------------------------------------------------
// Phase 3: Players, Movement, and Interactions
// ---------------------------------------------------------------------------

/// Sent by a client each frame to report its boolean player-state markers.
///
/// Replaces the boolean fields from the former `ExportStateMessage`.
/// Markers are insert/remove components rather than always-present value
/// components, so a dedicated message is used instead of
/// `ExportClientComponent<T>`.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct ExportPlayerMarkersMessage {
    pub is_hiding: bool,
    pub in_truck: bool,
    pub is_spectating: bool,
}

/// Sent by a client to request that the server authorize local simulation.
#[derive(Debug, Clone, Serialize, Deserialize, Message, Reflect)]
#[reflect(Default)]
pub struct RequestSimulationAuthority {
    pub entity: Entity,
}

impl Default for RequestSimulationAuthority {
    fn default() -> Self {
        Self {
            entity: Entity::PLACEHOLDER,
        }
    }
}

impl bevy::ecs::entity::MapEntities for RequestSimulationAuthority {
    fn map_entities<M: bevy::ecs::entity::EntityMapper>(&mut self, mapper: &mut M) {
        self.entity = mapper.get_mapped(self.entity);
    }
}

/// Sent by a client to request that the server revoke local simulation authority.
#[derive(Debug, Clone, Serialize, Deserialize, Message, Reflect)]
#[reflect(Default)]
pub struct RelieveSimulationAuthority {
    pub entity: Entity,
}

impl Default for RelieveSimulationAuthority {
    fn default() -> Self {
        Self {
            entity: Entity::PLACEHOLDER,
        }
    }
}

impl bevy::ecs::entity::MapEntities for RelieveSimulationAuthority {
    fn map_entities<M: bevy::ecs::entity::EntityMapper>(&mut self, mapper: &mut M) {
        self.entity = mapper.get_mapped(self.entity);
    }
}

/// Message sent by a client to request picking up a gear entity.
#[derive(Debug, Clone, Serialize, Deserialize, Message, Reflect)]
#[reflect(Default)]
pub struct RequestGrab {
    pub entity: Entity,
}

impl Default for RequestGrab {
    fn default() -> Self {
        Self {
            entity: Entity::PLACEHOLDER,
        }
    }
}

impl bevy::ecs::entity::MapEntities for RequestGrab {
    fn map_entities<M: bevy::ecs::entity::EntityMapper>(&mut self, mapper: &mut M) {
        self.entity = mapper.get_mapped(self.entity);
    }
}

/// Message sent by the client to the server to release ownership.
#[derive(Debug, Clone, Serialize, Deserialize, Message, Reflect)]
#[reflect(Default)]
pub struct RequestDrop {
    pub entity: Entity,
    pub position: [f32; 3],
    pub direction: [f32; 3],
}

impl Default for RequestDrop {
    fn default() -> Self {
        Self {
            entity: Entity::PLACEHOLDER,
            position: [0.0, 0.0, 0.0],
            direction: [0.0, 0.0, 0.0],
        }
    }
}

impl bevy::ecs::entity::MapEntities for RequestDrop {
    fn map_entities<M: bevy::ecs::entity::EntityMapper>(&mut self, mapper: &mut M) {
        self.entity = mapper.get_mapped(self.entity);
    }
}

/// Local-only Bevy event fired by `drop_object` on the authority (listen-server host)
/// when a player drops a gear item onto the floor.
///
/// This event never travels over the network — it is a signal from
/// `unplayer-plugin` to `unreplicon-plugin` so the network layer can broadcast
/// the floor-gear spawn to all connected join clients via `FloorGearSpawnBroadcast`.
#[derive(Debug, Clone, Message)]
pub struct HostFloorGearDroppedEvent {
    pub kind: GearKind,
    /// World-space position `[x, y, z]` where the gear was placed.
    pub pos: [f32; 3],
    /// Direction the gear is facing `[dx, dy, dz]` (from `DeployedGear.direction`).
    pub direction: [f32; 3],
}

/// Local-only Bevy event fired by `grab_object` on the authority (listen-server host)
/// when a player picks up a floor gear item.
///
/// This event never travels over the network — it is a signal from
/// `unplayer-plugin` to `unreplicon-plugin` so the network layer can broadcast
/// the floor-gear despawn to all connected join clients via `FloorGearDespawnBroadcast`.
#[derive(Debug, Clone, Message)]
pub struct HostFloorGearPickedUpEvent {
    /// World-space position `[x, y, z]` from which the gear was picked up.
    pub pos: [f32; 3],
}

/// Sent by a join client to notify the authority that the player dropped a salt pile.
///
/// On the authority this arrives as `FromClient<SaltDroppedMessage>`.
/// The authority spawns a `Replicated` `SaltPile` entity at the given position,
/// which bevy_replicon then replicates to all connected clients.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct SaltDroppedMessage {
    /// World-space position `[x, y, z, visual_priority]` where the salt was dropped.
    pub pos: [f32; 4],
}

/// Broadcast by the server to all join clients when a gear item is placed on the floor.
///
/// Clients spawn a local gear entity with `FloorItemCollidable`, `DeployedGear`, and
/// `EquipmentPosition::Deployed` so the item is visible and correctly oriented for lighting.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct FloorGearSpawnBroadcast {
    pub kind: GearKind,
    /// World-space position `[x, y, z]` where the gear was placed.
    pub pos: [f32; 3],
    /// Direction the gear is facing `[dx, dy, dz]`.
    pub direction: [f32; 3],
}

/// Broadcast by the server to all join clients when a floor gear item is picked up.
///
/// Clients find the nearest floor gear entity within ~0.6 units of `pos` and despawn it.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct FloorGearDespawnBroadcast {
    /// World-space position `[x, y, z]` from which the gear was picked up.
    pub pos: [f32; 3],
}

// ---------------------------------------------------------------------------
// Phase 4: Ghost, Evidence, and Mission messages
// ---------------------------------------------------------------------------

/// Broadcast by the server to all clients to spawn a visual particle effect.
///
/// Registered as a server → client message via `app.add_server_message`.
/// Clients receive this and spawn the particle entity locally.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct SpawnParticleNetEvent {
    /// Particle type identifier (currently only "smoke").
    pub particle_type: String,
    /// World-space position `[x, y, z]` at which to spawn the particle.
    pub position: [f32; 3],
}

/// Sent by the Authority when the ghost-talk RNG fires in `sound_update`
/// (the `gn == 0` block). All pure clients receive this and inject a
/// sound-field pulse into their local `SoundGrid` at the same time as the
/// Authority, synchronizing the *trigger timing* of ghost-induced sanity
/// pressure. Each client reconstructs the pulse independently with local RNG,
/// so the exact vector magnitudes are not identical across instances.
///
/// One message is sent per `SoundEmitter` entity that exists at the time of
/// the trigger (normally: ghost breach + ghost entity = two messages per event).
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct GhostSoundFieldBroadcast {
    /// World-space position of the emitter entity (breach or ghost).
    pub position: [f32; 3],
}

/// Local-only Bevy event emitted by the Hub UI layer when a room connection
/// is requested from the server. This event is listened to by the transport layer
/// (unreplicon-plugin) to handle the actual connection setup and mutation of
/// network state, rather than having the UI layer mutate global config directly.
///
/// This maintains the "Tell, Don't Ask" pattern: the UI layer (domain) emits
/// a signal; the transport layer (infrastructure) receives and acts on it.
#[derive(Debug, Clone, Message)]
pub struct HubConnectionRequested {
    pub address: String,
    /// The public hostname of the server, provided by the Hub API.
    pub server_hostname: Option<String>,
    pub ticket: Option<String>,
    pub cert_hash: Option<String>,
}

/// Sent by a client immediately after connection to provide their Hub ticket.
///
/// This is part of the post-connection handshake required because some
/// transports (like WebTransport) do not support a native connection payload.
#[derive(Debug, Clone, Serialize, Deserialize, Event)]
pub struct ConnectionTicketMessage {
    pub ticket: String,
    pub protocol_hash: String,
}
