use bevy::prelude::*;
use serde::{Deserialize, Serialize};

/// Sent by the (room-owner) client to request a map change.
///
/// On the server this arrives as `FromClient<RequestSelectMap>`.
/// The server validates ownership then updates `LobbyInfo.selected_map`.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct RequestSelectMap {
    pub map_filepath: String,
}

/// Sent by the (room-owner) client to request a difficulty change.
///
/// On the server this arrives as `FromClient<RequestSelectDifficulty>`.
/// The server validates ownership then updates `LobbyInfo.selected_difficulty`.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct RequestSelectDifficulty {
    pub difficulty_id: String,
}

/// Sent by the (room-owner) client to start the mission.
///
/// `map_seed` is generated by the sender so all peers use the same value.
/// On the server this arrives as `FromClient<RequestStartMission>`.
/// The server spawns a `(Replicated, SelectedMission)` entity which clients
/// observe to trigger level loading.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct RequestStartMission {
    pub map_seed: u64,
}
