use bevy::prelude::*;
use serde::{Deserialize, Serialize};
use unevents_core::events::roomchanged::InteractionExecutionType;
use unghost_core::types::evidence::Evidence;
use unghost_core::types::ghost::types::GhostType;

use crate::network_id::NetworkId;
use unfoundation_core::types::gear::Hand;
use ungear_core::types::gear::kind::GearKind;

/// Sent by the (room-owner) client to request a map change.
///
/// On the server this arrives as `FromClient<RequestSelectMap>`.
/// The server validates ownership then updates `LobbyInfo.selected_map`.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct RequestSelectMap {
    pub map_filepath: String,
}

/// Sent by the (room-owner) client to request a difficulty change.
///
/// On the server this arrives as `FromClient<RequestSelectDifficulty>`.
/// The server validates ownership then updates `LobbyInfo.selected_difficulty`.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct RequestSelectDifficulty {
    pub difficulty_id: String,
}

/// Sent by the (room-owner) client to start the mission.
///
/// `map_seed` is generated by the sender so all peers use the same value.
/// On the server this arrives as `FromClient<RequestStartMission>`.
/// The server spawns a `(Replicated, SelectedMission)` entity which clients
/// observe to trigger level loading.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct RequestStartMission {
    pub map_seed: u64,
}

// ---------------------------------------------------------------------------
// Phase 3: Players, Movement, and Interactions
// ---------------------------------------------------------------------------

/// Message sent by a client to report its owned entity state.
#[derive(Debug, Clone, Serialize, Deserialize, Message, Reflect, Default)]
#[reflect(Default)]
pub struct ExportStateMessage {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub is_running: bool,
    pub frame: u16,
    pub is_hiding: bool,
    pub stamina: f32,
    pub health: f32,
    pub sanity: f32,
    pub is_spectating: bool,
}

/// Message sent by the server to grant ownership of an entity to a client.
#[derive(Debug, Clone, Serialize, Deserialize, Message, Reflect)]
#[reflect(Default)]
pub struct OwnershipGranted {
    pub entity: Entity,
}

impl Default for OwnershipGranted {
    fn default() -> Self {
        Self {
            entity: Entity::PLACEHOLDER,
        }
    }
}

impl bevy::ecs::entity::MapEntities for OwnershipGranted {
    fn map_entities<M: bevy::ecs::entity::EntityMapper>(&mut self, mapper: &mut M) {
        self.entity = mapper.get_mapped(self.entity);
    }
}

/// Message sent by a client to request picking up a gear entity.
#[derive(Debug, Clone, Serialize, Deserialize, Message, Reflect)]
#[reflect(Default)]
pub struct RequestPickupGear {
    pub entity: Entity,
}

impl Default for RequestPickupGear {
    fn default() -> Self {
        Self {
            entity: Entity::PLACEHOLDER,
        }
    }
}

impl bevy::ecs::entity::MapEntities for RequestPickupGear {
    fn map_entities<M: bevy::ecs::entity::EntityMapper>(&mut self, mapper: &mut M) {
        self.entity = mapper.get_mapped(self.entity);
    }
}

/// Message sent by the client to the server to report its owned gear state.
#[derive(Debug, Clone, Serialize, Deserialize, Message, Reflect)]
#[reflect(Default)]
pub struct ExportGearStateMessage {
    pub entity: Entity,
    pub is_on: bool,
    pub battery: f32,
    pub temperature: f32,
}

impl Default for ExportGearStateMessage {
    fn default() -> Self {
        Self {
            entity: Entity::PLACEHOLDER,
            is_on: false,
            battery: 100.0,
            temperature: 20.0,
        }
    }
}

impl bevy::ecs::entity::MapEntities for ExportGearStateMessage {
    fn map_entities<M: bevy::ecs::entity::EntityMapper>(&mut self, mapper: &mut M) {
        self.entity = mapper.get_mapped(self.entity);
    }
}

/// Message sent by the client to the server to release ownership.
#[derive(Debug, Clone, Serialize, Deserialize, Message, Reflect)]
#[reflect(Default)]
pub struct OwnershipReleased {
    pub entity: Entity,
}

impl Default for OwnershipReleased {
    fn default() -> Self {
        Self {
            entity: Entity::PLACEHOLDER,
        }
    }
}

impl bevy::ecs::entity::MapEntities for OwnershipReleased {
    fn map_entities<M: bevy::ecs::entity::EntityMapper>(&mut self, mapper: &mut M) {
        self.entity = mapper.get_mapped(self.entity);
    }
}

/// Sent each frame by a non-host client to report its current position and state.
///
/// Sent over `Channel::Unreliable` (best-effort, unordered).
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct PlayerMoveMessage {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub is_running: bool,
    /// Current animation frame index (for remote character animation sync).
    pub frame: u16,
    pub is_hiding: bool,
    pub stamina: f32,
    pub health: f32,
    pub sanity: f32,
}

/// Sent by a client to request an interactive-object state change.
///
/// Uses board-space integer coordinates to identify the target entity in a
/// map-stable way (all clients load the same map from the same seed).
/// The server finds the entity at `position`, validates the request, and fires
/// `ExecuteInteractionEvent` locally.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct InteractionRequestMessage {
    /// Board-space position (`[x, y, z]`) of the interactive entity.
    pub position: [i32; 3],
    /// Whether to change state or only read the current room state.
    pub ietype: InteractionExecutionType,
    /// If `Some`, force the interaction to transition to this specific tile UID.
    pub force_tuid: Option<u32>,
}

/// Broadcast by the server to all join clients (excluding the originator) to
/// notify them of a remote player's interaction with an interactive map object.
///
/// Registered as a server → client message via `app.add_server_message`.
/// Clients receive this and fire `ExecuteInteractionEvent` on the matching local
/// entity, keeping door/switch state in sync across all nodes.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct RemoteInteractionBroadcast {
    /// Board-space position of the interactive entity (same coordinate system
    /// as `InteractionRequestMessage::position`).
    pub position: [i32; 3],
    pub ietype: InteractionExecutionType,
    pub force_tuid: Option<u32>,
}

/// One loadout action a join client can request from the server during the truck phase.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TruckLoadoutAction {
    /// Equip a gear item from the van inventory into the first free slot.
    AddGear(GearKind),
    /// Unequip the item currently held in the given hand.
    ClearHand(Hand),
    /// Unequip the backpack item at the given index.
    ClearInventorySlot(usize),
}

/// Sent by a join client to request a loadout change during the truck phase.
///
/// The server processes each action and applies the same spawn/despawn logic
/// as the host-local `button_clicked` handler, ensuring the server's copy of
/// the player's `PlayerGear` reflects the chosen loadout.
/// Transmitted on `Channel::Ordered` for reliability.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct TruckLoadoutMessage {
    pub action: TruckLoadoutAction,
}

/// Local-only Bevy event fired by `player_interaction_system` on the authority
/// (listen-server host) when the host player interacts with an object.
///
/// This event never travels over the network — it is a signal from
/// `unplayer-plugin` to `unreplicon-plugin` so the network layer can broadcast
/// the change to all connected join clients via `RemoteInteractionBroadcast`.
#[derive(Debug, Clone, Message)]
pub struct HostInteractionOccurred {
    /// Board-space position of the interactive entity.
    pub position: [i32; 3],
    pub ietype: InteractionExecutionType,
    pub force_tuid: Option<u32>,
}

/// Local-only Bevy event fired by `watch_tween_insertions` on the authority
/// whenever a `Tween` component is added to any map entity.
///
/// Never travels over the network. `unreplicon-plugin` reads this and
/// broadcasts `MovableMotionBroadcast` to all connected join clients so they
/// can replay the same animation locally.
#[derive(Debug, Clone, Message)]
pub struct HostMovableMotionEvent {
    /// Board-space original spawn position of the entity
    /// (from `NetworkOriginalMapPosition`), used for entity lookup on clients.
    pub map_bpos: [i32; 3],
    /// World-space start position `[x, y, z, visual_priority]`.
    pub start: [f32; 4],
    /// World-space end position `[x, y, z, visual_priority]`.
    pub end: [f32; 4],
    /// Animation duration in seconds.
    pub duration: f32,
    /// Ease function: 0 = Linear, 1 = ParabolicArc, 2 = SineEaseOut.
    pub ease: u8,
}

/// Broadcast by the server to all join clients when a ghost interaction moves
/// a map object (throw, nudge, haunted-move). Clients replay the same tween
/// animation locally to keep visual state in sync.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct MovableMotionBroadcast {
    /// Board-space original spawn position of the entity.
    pub map_bpos: [i32; 3],
    /// World-space start position `[x, y, z, visual_priority]`.
    pub start: [f32; 4],
    /// World-space end position `[x, y, z, visual_priority]`.
    pub end: [f32; 4],
    /// Animation duration in seconds.
    pub duration: f32,
    /// Ease function: 0 = Linear, 1 = ParabolicArc, 2 = SineEaseOut.
    pub ease: u8,
}

/// Local-only Bevy event fired by `drop_object` on the authority (listen-server host)
/// when a player drops a gear item onto the floor.
///
/// This event never travels over the network — it is a signal from
/// `unplayer-plugin` to `unreplicon-plugin` so the network layer can broadcast
/// the floor-gear spawn to all connected join clients via `FloorGearSpawnBroadcast`.
#[derive(Debug, Clone, Message)]
pub struct HostFloorGearDroppedEvent {
    pub kind: GearKind,
    /// World-space position `[x, y, z]` where the gear was placed.
    pub pos: [f32; 3],
    /// Direction the gear is facing `[dx, dy, dz]` (from `DeployedGear.direction`).
    pub direction: [f32; 3],
}

/// Local-only Bevy event fired by `grab_object` on the authority (listen-server host)
/// when a player picks up a floor gear item.
///
/// This event never travels over the network — it is a signal from
/// `unplayer-plugin` to `unreplicon-plugin` so the network layer can broadcast
/// the floor-gear despawn to all connected join clients via `FloorGearDespawnBroadcast`.
#[derive(Debug, Clone, Message)]
pub struct HostFloorGearPickedUpEvent {
    /// World-space position `[x, y, z]` from which the gear was picked up.
    pub pos: [f32; 3],
}

/// Broadcast by the server to all join clients when a gear item is placed on the floor.
///
/// Clients spawn a local gear entity with `FloorItemCollidable`, `DeployedGear`, and
/// `EquipmentPosition::Deployed` so the item is visible and correctly oriented for lighting.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct FloorGearSpawnBroadcast {
    pub kind: GearKind,
    /// World-space position `[x, y, z]` where the gear was placed.
    pub pos: [f32; 3],
    /// Direction the gear is facing `[dx, dy, dz]`.
    pub direction: [f32; 3],
}

/// Broadcast by the server to all join clients when a floor gear item is picked up.
///
/// Clients find the nearest floor gear entity within ~0.6 units of `pos` and despawn it.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct FloorGearDespawnBroadcast {
    /// World-space position `[x, y, z]` from which the gear was picked up.
    pub pos: [f32; 3],
}

// ---------------------------------------------------------------------------
// Phase 4: Ghost, Evidence, and Mission messages
// ---------------------------------------------------------------------------

/// Broadcast by the server to all clients to spawn a visual particle effect.
///
/// Registered as a server → client message via `app.add_server_message`.
/// Clients receive this and spawn the particle entity locally.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct SpawnParticleNetEvent {
    /// Particle type identifier (currently only "smoke").
    pub particle_type: String,
    /// World-space position `[x, y, z]` at which to spawn the particle.
    pub position: [f32; 3],
}

/// Sent by a client to toggle evidence in the shared journal.
///
/// The server validates this, updates `GhostGuess`, and the change propagates
/// to all clients via replication.
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct RequestJournalEvidenceToggle {
    pub evidence: Evidence,
    pub mark_as_found: bool,
}

/// Sent by a client to update the ghost-type guess in the shared journal.
///
/// `ghost_type = None` means "clear the current guess".
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct RequestJournalGhostToggle {
    pub ghost_type: Option<GhostType>,
}

/// Local event fired when a player dies (server-authoritative).
///
/// Written by the health / sanity system when a player's HP reaches zero.
/// Read by death-handling systems (e.g. spectator mode activation).
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct PlayerDiedEvent {
    pub id: NetworkId,
}

/// Sent by the Authority when the ghost-talk RNG fires in `sound_update`
/// (the `gn == 0` block). All pure clients receive this and inject a matching
/// sound-field pulse into their local `SoundGrid`, synchronizing ghost-induced
/// sanity pressure across all instances.
///
/// One message is sent per `SoundEmitter` entity that exists at the time of
/// the trigger (normally: ghost breach + ghost entity = two messages per event).
#[derive(Debug, Clone, Serialize, Deserialize, Message)]
pub struct GhostSoundFieldBroadcast {
    /// World-space position of the emitter entity (breach or ghost).
    pub position: [f32; 3],
}
