[package]
name = "untruck"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
uncore = { path = "../uncore" }
unstd = { path = "../unstd" }
ungear = { path = "../ungear" }
ungearitems = { path = "../ungearitems" }
unsettings = { path = "../unsettings" }
unprofile = { path = "../unprofile" }
unwalkiecore = { path = "../unwalkiecore" }

bevy = { workspace = true }
bevy_kira_audio = { workspace = true }
bevy_platform = { workspace = true }
rand = { workspace = true }
fastapprox = { workspace = true }
ordered-float = { workspace = true }
bevy-persistent = { workspace = true }
enum-iterator = { workspace = true }
