[package]
name = "uninventory-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
unplayer-core = { workspace = true }
untypes-core = { workspace = true }
ungear-core = { workspace = true }
unspatial-core = { workspace = true }
unboard-core = { workspace = true }
unreplicon-core = { workspace = true }
unaudiospatial-core = { workspace = true }
unbehavior = { workspace = true }
unrender-std = { workspace = true }
