[package]
name = "unengine-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unfoundation-core = { path = "../unfoundation-core" }
unengine-core = { path = "../unengine-core" }
untypes-core = { path = "../untypes-core" }
unui-core = { path = "../unui-core" }
unrender-std = { path = "../unrender-std" }
unboard-core = { path = "../unboard-core" }
unbehavior = { path = "../unbehavior" }
unevents-core = { path = "../unevents-core" }
unspatial-core = { path = "../unspatial-core" }
unassets-core = { path = "../unassets-core" }
unnoise-core = { path = "../unnoise-core" }
unreplicon-core = { workspace = true }

bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
bevy_replicon = { workspace = true }
