[package]
name = "unengine-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unfoundation-core = { path = "../unfoundation-core" }
unengine-core = { path = "../unengine-core" }
untypes-core = { path = "../untypes-core" }
unui-core = { path = "../unui-core" }
unrender-std = { path = "../unrender-std" }

bevy = { workspace = true }
