[package]
name = "unevents-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
unboard-core = { path = "../unboard-core" }
unspatial-core = { path = "../unspatial-core" }
bevy = { workspace = true }
bevy_platform = { workspace = true }
