[package]
name = "ungearitems"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]

unspatial-core = { path = "../unspatial-core" }
undifficulty-core = { path = "../undifficulty-core" }
uncore-foundation = { path = "../uncore-foundation" }
uncore-board = { path = "../uncore-board" }
uncore-types = { path = "../uncore-types" }
uncore-components = { path = "../uncore-components" }
uncore-resources = { path = "../uncore-resources" }
unrender = { path = "../unrender" }
unmetrics-core = { path = "../unmetrics-core" }
ungear = { path = "../ungear" }
untags-core = { path = "../untags-core" }
unghost-core = { path = "../unghost-core" }
unplayer-core = { path = "../unplayer-core" }

bevy = { workspace = true }
bevy_platform = { workspace = true }
rand = { workspace = true }
ndarray = { workspace = true }
enum-iterator = { workspace = true }
fastapprox = { workspace = true }
