[package]
name = "unassets-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
untypes-core = { path = "../untypes-core" }
bevy = { workspace = true }
bevy_platform = { workspace = true }
thiserror = { workspace = true }
