[package]
name = "unplayer-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true


[lints]
workspace = true

[dependencies]
undifficulty-core = { path = "../undifficulty-core" }
unbehavior = { path = "../unbehavior" }
unfoundation-core = { path = "../unfoundation-core" }
unboard-core = { path = "../unboard-core" }
unlight-core = { path = "../unlight-core" }
unplayer-core = { path = "../unplayer-core" }
untypes-core = { path = "../untypes-core" }
unsummary-core = { path = "../unsummary-core" }
unnavigation-core = { path = "../unnavigation-core" }
unui-core = { path = "../unui-core" }
unfog-core = { path = "../unfog-core" }
unrender-std = { path = "../unrender-std" }
unrender-core = { path = "../unrender-core" }
uninteraction-core = { path = "../uninteraction-core" }
untruck-core = { path = "../untruck-core" }
ungear-core = { path = "../ungear-core" }
unnpc-core = { path = "../unnpc-core" }
unaudiospatial-core = { path = "../unaudiospatial-core" }
unsoundfield-core = { path = "../unsoundfield-core" }
unghost-core = { path = "../unghost-core" }
untags-core = { path = "../untags-core" }

unreplicon-core = { workspace = true }
unprofile-core = { path = "../unprofile-core" }
unspatial-core = { path = "../unspatial-core" }
unthermal-core = { path = "../unthermal-core" }

bevy = { workspace = true }
bevy_platform = { workspace = true }
bevy-persistent = { workspace = true }
bevy_asset_loader = { workspace = true }
