[package]
name = "unplayer-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true


[lints]
workspace = true

[dependencies]
undifficulty-core = { path = "../undifficulty-core" }
unbehavior = { path = "../unbehavior" }
unfoundation-core = { path = "../unfoundation-core" }
unboard-core = { path = "../unboard-core" }
unlight-plugin = { path = "../unlight-plugin" }
unevents-core = { path = "../unevents-core" }
unplayer-core = { path = "../unplayer-core" }
untypes-core = { path = "../untypes-core" }
unsummary-core = { path = "../unsummary-core" }
unnavigation-core = { path = "../unnavigation-core" }
unui-core = { path = "../unui-core" }
untags-core = { path = "../untags-core" }
unfog-core = { path = "../unfog-core" }
unrender-std = { path = "../unrender-std" }
uninteraction-core = { path = "../uninteraction-core" }
ungear-core = { path = "../ungear-core" }
unsettings-core = { path = "../unsettings-core" }
unprofile-core = { path = "../unprofile-core" }
unspatial-core = { path = "../unspatial-core" }
unthermal-core = { path = "../unthermal-core" }
unsound-core = { path = "../unsound-core" }

bevy = { workspace = true }
bevy_platform = { workspace = true }
bevy-persistent = { workspace = true }
bevy_asset_loader = { workspace = true }
