[package]
name = "unplayer-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true


[lints]
workspace = true

[dependencies]
unbehavior-core = { workspace = true }
unmapload-core = { workspace = true }
unboard-core = { workspace = true }
unplayer-core = { workspace = true }
unlocomotion-core = { workspace = true }
uninput-core = { workspace = true }
unorchestrator-core = { workspace = true }
unnavigation-core = { workspace = true }
unrender-std = { workspace = true }
uninteraction-core = { workspace = true }
ungear-core = { workspace = true }
unaudiospatial-core = { workspace = true }
unreplicon-core = { workspace = true }
unspatial-core = { workspace = true }
untruck-core = { workspace = true }

bevy = { workspace = true }
bevy_replicon = { workspace = true }
bevy_platform = { workspace = true }
bevy_asset_loader = { workspace = true }
