[package]
name = "ghost_list"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]

unghost-core = { path = "../../unghost-core" }
enum-iterator = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
csv = { workspace = true }
