[package]
name = "unrender-std"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
unbehavior-core = { workspace = true }
ungear-core = { workspace = true }
enum-iterator = { workspace = true }
bevy_platform = { workspace = true }
