pub mod compass;
pub mod emfmeter;
pub mod estaticmeter;
pub mod flashlight;
pub mod geigercounter;
pub mod ionmeter;
pub mod motionsensor;
pub mod photocam;
pub mod prelude;
pub mod quartz;
pub mod recorder;
pub mod redtorch;
pub mod repellentflask;
pub mod sage;
pub mod salt;
pub mod spiritbox;
pub mod thermalimager;
pub mod thermometer;
pub mod uvtorch;
pub mod videocam;
pub mod plugin;
pub mod from_gearkind;

use crate::gear::ext::types::gear::Gear;
use uncore::systemparam::gear_stuff::GearStuff;
use uncore::traits::gear_usable::GearUsable;
use uncore::types::gear::spriteid::GearSpriteID;
use uncore::types::gear::utils::on_off;
use uncore::types::gear_kind::GearKind;
