[package]
name = "unaudiospatial-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unaudiospatial-core = { workspace = true }
unspatial-core = { workspace = true }
unsettings-core = { workspace = true }
untags-core = { workspace = true }
unmetrics-core = { workspace = true }
untypes-core = { workspace = true }

bevy = { workspace = true }
bevy-persistent = { workspace = true }
