[package]
name = "unaudiospatial-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
uncommon-states-core = { workspace = true }

unaudiospatial-core = { workspace = true }
unspatial-core = { workspace = true }
unsettings-core = { workspace = true }
unmetrics-core = { workspace = true }
bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
bevy_seedling = { workspace = true }
bevy-persistent = { workspace = true }
