[package]
name = "unaudiospatial-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unaudiospatial-core = { path = "../unaudiospatial-core" }
unspatial-core = { path = "../unspatial-core" }
unsettings-core = { path = "../unsettings-core" }
untags-core = { path = "../untags-core" }
unmetrics-core = { path = "../unmetrics-core" }
untypes-core = { path = "../untypes-core" }

bevy = { workspace = true }
bevy-persistent = { workspace = true }
