[package]
name = "undifficulty-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
uncore-foundation = { path = "../uncore-foundation" }
uncore-types = { path = "../uncore-types" }
bevy = { workspace = true }
bevy_platform = { workspace = true }
serde = { workspace = true }
enum-iterator = { workspace = true }
