[package]
name = "unclassic-mode-render-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unbehavior = { path = "../unbehavior" }
unboard-core = { path = "../unboard-core" }
unghost-core = { path = "../unghost-core" }
unnavigation-core = { path = "../unnavigation-core" }
unplayer-core = { path = "../unplayer-core" }
unmapload-core = { path = "../unmapload-core" }
unpicking-core = { path = "../unpicking-core" }
unsoundfield-core = { path = "../unsoundfield-core" }
unrender-std = { path = "../unrender-std" }
unreplicon-core = { workspace = true }
unsettings-core = { path = "../unsettings-core" }
unspatial-core = { path = "../unspatial-core" }
untags-core = { path = "../untags-core" }
untmxmap-core = { path = "../untmxmap-core" }
untypes-core = { path = "../untypes-core" }
unrender-core = { path = "../unrender-core" }
bevy = { workspace = true }
bevy-persistent = { workspace = true }
bevy_replicon = { workspace = true }
