[package]
name = "unclassic-mode-render-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unclassic-mode-core = { workspace = true }
unbehavior-core = { workspace = true }
unboard-core = { workspace = true }
unlocomotion-core = { workspace = true }
unghost-core = { workspace = true }
uninput-core = { workspace = true }
unlight-core = { workspace = true }
unnavigation-core = { workspace = true }
unplayer-core = { workspace = true }
unmapload-core = { workspace = true }
unpicking-core = { workspace = true }
unsoundfield-core = { workspace = true }
unsensing-core = { workspace = true }
unrender-std = { workspace = true }
unreplicon-core = { workspace = true }
unsettings-core = { workspace = true }
unspatial-core = { workspace = true }
untmxmap-core = { workspace = true }
uncommon-app-core = { workspace = true }
bevy = { workspace = true }
bevy-persistent = { workspace = true }
bevy_replicon = { workspace = true }
