[package]
name = "unhaunter-gearitems-logic"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
bevy_replicon = { workspace = true }
unboard-core = { workspace = true }
uncommon-states-core = { workspace = true }
undifficulty-core = { workspace = true }
uncommon-app-core = { workspace = true }
ungear-core = { workspace = true }
ungearitems-core = { workspace = true }
unghost-core = { workspace = true }
uninteraction-core = { workspace = true }
unmetrics-core = { workspace = true }
unreplicon-core = { workspace = true }
unspatial-core = { workspace = true }
rand = { workspace = true }
enum-iterator = { workspace = true }
