[package]
name = "untiled-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
unrender-std = { path = "../unrender-std" }
bevy = { workspace = true }
bevy_platform = { workspace = true }
tiled = { workspace = true }
