[package]
name = "unsound-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unsound-core = { path = "../unsound-core" }
unspatial-core = { path = "../unspatial-core" }
unfoundation-core = { path = "../unfoundation-core" }
unboard-core = { path = "../unboard-core" }
unmetrics-core = { path = "../unmetrics-core" }
untypes-core = { path = "../untypes-core" }
unbehavior = { path = "../unbehavior" }
unmapload-core = { path = "../unmapload-core" }
unreplicon-core = { workspace = true }
bevy_replicon   = { workspace = true }

bevy = { workspace = true }
rand = { workspace = true }
