[package]
name = "unmainmenu-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]

unorchestrator-core = { workspace = true }
unreplicon-core = { workspace = true }
uncommon-app-core = { workspace = true }
unmenu-core = { workspace = true }
unprofile-core = { workspace = true }
unmaphub-core = { workspace = true }

bevy = { workspace = true }
bevy-persistent = { workspace = true }
