[package]
name = "unwalkie-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]

unspatial-core = { path = "../unspatial-core" }
uninteraction-core = { path = "../uninteraction-core" }
undifficulty-core = { path = "../undifficulty-core" }
unfoundation-core = { path = "../unfoundation-core" }
unboard-core = { path = "../unboard-core" }
unevents-core = { path = "../unevents-core" }
untypes-core = { path = "../untypes-core" }
unui-core = { path = "../unui-core" }
ungear-core = { path = "../ungear-core" }
ungearitems-core = { path = "../ungearitems-core" }
unsettings-core = { path = "../unsettings-core" }
unwalkie-types = { path = "../unwalkie-types" }
unwalkie-core = { path = "../unwalkie-core" }
unprofile-core = { path = "../unprofile-core" }
untruck-core = { path = "../untruck-core" }
unplayer-core = { path = "../unplayer-core" }
unrender-std = { path = "../unrender-std" }
unghost-core = { path = "../unghost-core" }

bevy = { workspace = true }
bevy_platform = { workspace = true }
rand = { workspace = true }
bevy-persistent = { workspace = true }
enum-iterator = { workspace = true }
