[package]
name = "unwalkie-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]

unspatial-core = { workspace = true }
unboard-core = { workspace = true }
unbehavior = { workspace = true }
uninteraction-core = { workspace = true }
undifficulty-core = { workspace = true }
unfoundation-core = { workspace = true }
unlight-core = { workspace = true }
untypes-core = { workspace = true }
unui-core = { workspace = true }
ungear-core = { workspace = true }
ungearitems-core = { workspace = true }
unsettings-core = { workspace = true }
unwalkie-types = { workspace = true }
unwalkie-core = { workspace = true }
unprofile-core = { workspace = true }
untruck-core = { workspace = true }
unplayer-core = { workspace = true }
unrender-std = { workspace = true }
unghost-core = { workspace = true }
unmetrics-core = { workspace = true }
unmapload-core = { workspace = true }

bevy = { workspace = true }
bevy_platform = { workspace = true }
rand = { workspace = true }
bevy-persistent = { workspace = true }
enum-iterator = { workspace = true }
