[package]
name = "unfog-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[dependencies]

unspatial-core = { path = "../unspatial-core" }
uncore-assets = { path = "../uncore-assets" }
uncore-foundation = { path = "../uncore-foundation" }
uncore-board = { path = "../uncore-board" }
uncore-events = { path = "../uncore-events" }
uncore-types = { path = "../uncore-types" }
uncore-resources = { path = "../uncore-resources" }
unrender = { path = "../unrender" }
unplayer-core = { path = "../unplayer-core" }
unmetrics-core = { path = "../unmetrics-core" }
unnoise-core = { path = "../unnoise-core" }
unghost = { path = "../unghost" }
unghost-core = { path = "../unghost-core" }

bevy = { workspace = true }
bevy_platform = { workspace = true }
rand = { workspace = true }
ndarray = { workspace = true }