[package]
name = "unboard-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unspatial-core = { path = "../unspatial-core" }
unbehavior = { path = "../unbehavior" }
unfoundation-core = { path = "../unfoundation-core" }
bevy = { workspace = true }
bevy_platform = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
fastapprox = { workspace = true }
ordered-float = { workspace = true }
anyhow = { workspace = true }
ndarray = { workspace = true }
