[package]
name = "unnet-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unprofile-core = { path = "../unprofile-core" }
unnet-core = { path = "../unnet-core" }
untypes-core = { path = "../untypes-core" }
unplayer-core = { path = "../unplayer-core" }
unspatial-core = { path = "../unspatial-core" }
unfoundation-core = { path = "../unfoundation-core" }
untags-core = { path = "../untags-core" }
unevents-core = { path = "../unevents-core" }
undifficulty-core = { path = "../undifficulty-core" }
unghost-core = { path = "../unghost-core" }
untruck-core = { path = "../untruck-core" }
untruck-plugin = { path = "../untruck-plugin" }
unmetrics-core = { path = "../unmetrics-core" }
unsummary-core = { path = "../unsummary-core" }
ungear-core = { path = "../ungear-core" }
ungearitems-core = { path = "../ungearitems-core" }
unbehavior = { path = "../unbehavior" }
unboard-core = { path = "../unboard-core" }
uninteraction-core = { path = "../uninteraction-core" }
unrender-std = { path = "../unrender-std" }
unassets-core = { path = "../unassets-core" }
unsettings-core = { path = "../unsettings-core" }
unnavigation-core = { path = "../unnavigation-core" }
rand = { workspace = true }
bevy = { workspace = true }
bevy-persistent = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
