[package]
name = "unnet-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unnet-core = { path = "../unnet-core" }
untypes-core = { path = "../untypes-core" }
unplayer-core = { path = "../unplayer-core" }
unspatial-core = { path = "../unspatial-core" }
unfoundation-core = { path = "../unfoundation-core" }
untags-core = { path = "../untags-core" }
unevents-core = { path = "../unevents-core" }
undifficulty-core = { path = "../undifficulty-core" }
unbehavior = { path = "../unbehavior" }
unboard-core = { path = "../unboard-core" }
uninteraction-core = { path = "../uninteraction-core" }
unrender-std = { path = "../unrender-std" }
bevy = { workspace = true }
serde_json = { workspace = true }
