[package]
name = "unthermal-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unthermal-core = { path = "../unthermal-core" }
unboard-core = { path = "../unboard-core" }
unspatial-core = { path = "../unspatial-core" }
unfoundation-core = { path = "../unfoundation-core" }
unmapload-core = { path = "../unmapload-core" }
unevents-core = { path = "../unevents-core" }
unmetrics-core = { path = "../unmetrics-core" }
untypes-core = { path = "../untypes-core" }
undifficulty-core = { path = "../undifficulty-core" }
unbehavior = { path = "../unbehavior" }
unsettings-core = { path = "../unsettings-core" }
bevy = { workspace = true }
bevy-persistent = { workspace = true }
bevy_platform = { workspace = true }
ndarray = { workspace = true }
rand = { workspace = true }
