[package]
name = "unpause-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
uninput-core = { workspace = true }
uncommon-app-core = { workspace = true }
unrender-std = { workspace = true }
unreplicon-core = { workspace = true }
unmission-core = { workspace = true }
