[package]
name = "unclassic-mode-gameplay-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
uncommon-states-core = { workspace = true }
unclassic-mode-core = { workspace = true }
unbehavior-core = { workspace = true }
unboard-core = { workspace = true }
undifficulty-core = { workspace = true }
ungear-core = { workspace = true }
unghost-core = { workspace = true }
uninvestigation-core = { workspace = true }
uninteraction-core = { workspace = true }
unlight-core = { workspace = true }
unplayer-core = { workspace = true }
unspatial-core = { workspace = true }
untmxmap-core = { workspace = true }
untruck-core = { workspace = true }
unmission-core = { workspace = true }
unreplicon-core = { workspace = true }
bevy = { workspace = true }
bevy_platform = { workspace = true }
