[package]
name = "unclassic-mode-gameplay-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
unbehavior-core = { workspace = true }
unboard-core = { workspace = true }
undifficulty-core = { workspace = true }
ungear-core = { workspace = true }
unghost-core = { workspace = true }
uninteraction-core = { workspace = true }
unlight-core = { workspace = true }
unplayer-core = { workspace = true }
unrender-std = { workspace = true }
unspatial-core = { workspace = true }
untags-core = { workspace = true }
untmxmap-core = { workspace = true }
untypes-core = { workspace = true }
bevy = { workspace = true }
bevy_platform = { workspace = true }
