[package]
name = "unhub-client"
version.workspace = true
edition.workspace = true
description = "Hub client library for Unhaunter"
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
uuid = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
postcard = { workspace = true }
hmac = { workspace = true }
anyhow = { workspace = true }
