[package]
name = "unhub-plugin"
version.workspace = true
edition.workspace = true
description = "Hub and ProcMan integration for Unhaunter"
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bevy = { workspace = true }
unhub-client = { workspace = true }
untypes-core = { workspace = true }
untags-core = { workspace = true }
unreplicon-core = { workspace = true }
unmenu-core = { workspace = true }
unui-core = { workspace = true }
unprofile-core = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
crossbeam-channel = { workspace = true }
uuid = { workspace = true }
bevy-persistent = { workspace = true }
rand = { workspace = true }
