[package]
name = "unhub-plugin"
version.workspace = true
edition.workspace = true
description = "Hub and ProcMan integration for Unhaunter"
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bevy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
unhub-client = { workspace = true }
untypes-core = { workspace = true }
unreplicon-core = { path = "../unreplicon-core" }
unmenu-core = { workspace = true }
unengine-core = { workspace = true }
unui-core = { workspace = true }
unprofile-core = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
crossbeam-channel = { workspace = true }
uuid = { workspace = true }
bevy-persistent = { workspace = true }
rand = { workspace = true }
