[package]
name = "unhub-plugin"
version.workspace = true
edition.workspace = true
description = "Hub and ProcMan integration for Unhaunter"
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
uncommon-states-core = { workspace = true }
bevy = { workspace = true }
unhub-client = { workspace = true }
uncommon-app-core = { workspace = true }
unreplicon-core = { workspace = true }
unmenu-core = { workspace = true }
bevy_replicon = { workspace = true }

unprofile-core = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
crossbeam-channel = { workspace = true }
uuid = { workspace = true }
bevy-persistent = { workspace = true }
serde_json = { workspace = true }
