[package]
name = "unreplicon-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
bevy_replicon = { workspace = true }
bevy_replicon_renet = { workspace = true }
bevy_renet = { workspace = true }
serde_json = { workspace = true }
crossbeam-channel = { workspace = true }
unhub-client = { workspace = true }
untypes-core = { workspace = true }
unreplicon-core = { workspace = true }
unprofile-core = { path = "../unprofile-core" }
uuid = { workspace = true }
base64 = { workspace = true }

undifficulty-core = { path = "../undifficulty-core" }
unmapload-core = { workspace = true }
unnavigation-core = { path = "../unnavigation-core" }
unrender-std = { path = "../unrender-std" }
unspatial-core = { path = "../unspatial-core" }
unplayer-core = { path = "../unplayer-core" }
untruck-core = { path = "../untruck-core" }
unboard-core = { path = "../unboard-core" }
uninteraction-core = { path = "../uninteraction-core" }
unghost-core = { path = "../unghost-core" }
untags-core = { path = "../untags-core" }
ungearitems-core = { path = "../ungearitems-core" }
ungear-core = { path = "../ungear-core" }
unsummary-core = { path = "../unsummary-core" }
unfoundation-core = { path = "../unfoundation-core" }
unbehavior = { path = "../unbehavior" }
