[package]
name = "unreplicon-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
bevy_replicon = { workspace = true }
bevy_replicon_renet = { workspace = true }
bevy_renet = { workspace = true }
untypes-core = { workspace = true }
uuid = { workspace = true }

unreplicon-core = { workspace = true }
unreplicon-transport = { workspace = true }
unlocomotion-core = { workspace = true }
unbehavior-core = { workspace = true }
undifficulty-core = { workspace = true }
unmapload-core = { workspace = true }
unmission-core = { workspace = true }
unrender-std = { workspace = true }
unspatial-core = { workspace = true }
unplayer-core = { workspace = true }
unvitals-core = { workspace = true }
untruck-core = { workspace = true }
unboard-core = { workspace = true }
uninteraction-core = { workspace = true }
unghost-core = { workspace = true }
untags-core = { workspace = true }
ungearitems-core = { workspace = true }
ungear-core = { workspace = true }
unfoundation-core = { workspace = true }
