[package]
name = "unghost-logic"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
uncommon-states-core = { workspace = true }

uncommon-app-core = { workspace = true }
unmapload-core = { workspace = true }
undifficulty-core = { workspace = true }
unaudiobg-core = { workspace = true }
unbehavior-core = { workspace = true }
unboard-core = { workspace = true }
unmission-core = { workspace = true }
unlight-core = { workspace = true }
unsoundfield-core = { workspace = true }
unaudiospatial-core = { workspace = true }
unplayer-core = { workspace = true }
unvitals-core = { workspace = true }
unmetrics-core = { workspace = true }
unnoise-core = { workspace = true }
uninteraction-core = { workspace = true }
ungearitems-core = { workspace = true }
unspatial-core = { workspace = true }
unghost-core = { workspace = true }
uninvestigation-core = { workspace = true }
untruck-core = { workspace = true }
unreplicon-core = { workspace = true }
bevy = { workspace = true }
bevy_replicon = { workspace = true }
rand = { workspace = true }
