[package]
name = "unghost-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
untypes-core = { path = "../untypes-core" }
undifficulty-core = { path = "../undifficulty-core" }
unbehavior = { path = "../unbehavior" }
unfoundation-core = { path = "../unfoundation-core" }
unboard-core = { path = "../unboard-core" }
unevents-core = { path = "../unevents-core" }
unsummary-core = { path = "../unsummary-core" }
unrender-std = { path = "../unrender-std" }
unplayer-core = { path = "../unplayer-core" }
unmetrics-core = { path = "../unmetrics-core" }
unnoise-core = { path = "../unnoise-core" }
uninteraction-core = { path = "../uninteraction-core" }
ungear-core = { path = "../ungear-core" }
ungearitems-core = { path = "../ungearitems-core" }
untags-core = { path = "../untags-core" }
unspatial-core = { path = "../unspatial-core" }
unghost-core = { path = "../unghost-core" }

bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
rand = { workspace = true }
