[package]
name = "unreplicon-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
unevents-core = { path = "../unevents-core" }
ungear-core = { path = "../ungear-core" }
ungearitems-core = { path = "../ungearitems-core" }
unfoundation-core = { path = "../unfoundation-core" }
unghost-core = { path = "../unghost-core" }
unbehavior = { path = "../unbehavior" }
