[package]
name = "untruckui-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
uncommon-states-core = { workspace = true }
unclassic-mode-core = { workspace = true }
untruck-core = { workspace = true }
undifficulty-core = { workspace = true }
uncommon-app-core = { workspace = true }
unmission-core = { workspace = true }
unplayer-core = { workspace = true }
unvitals-core = { workspace = true }
unrender-std = { workspace = true }
ungear-core = { workspace = true }
ungearitems-core = { workspace = true }
uninput-core = { workspace = true }
unprofile-core = { workspace = true }
unreplicon-core = { workspace = true }
unwalkie-core = { workspace = true }
unghost-core = { workspace = true }
uninvestigation-core = { workspace = true }
unmapload-core = { workspace = true }
unaudiospatial-core = { workspace = true }

bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
bevy_platform = { workspace = true }
bevy-persistent = { workspace = true }
uuid = { workspace = true }
