[package]
name = "unsummary"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[dependencies]
bevy = { workspace = true }

undifficulty = { path = "../undifficulty" }
uncore-assets = { path = "../uncore-assets" }
uncore-foundation = { path = "../uncore-foundation" }
uncore-board = { path = "../uncore-board" }
uncore-types = { path = "../uncore-types" }
uncore-resources = { path = "../uncore-resources" }
unui-core = { path = "../unui-core" }
bevy-persistent = { workspace = true }
unprofile-core = { path = "../unprofile-core" }
unplayer = { path = "../unplayer" }
