[package]
name = "unsummary"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[dependencies]
bevy = { workspace = true }

undifficulty = { path = "../undifficulty" }
uncore-foundation = { path = "../uncore-foundation" }
uncore-types = { path = "../uncore-types" }
uncore-resources = { path = "../uncore-resources" }
uncore-components = { path = "../uncore-components" }
uncore-systems = { path = "../uncore-systems" }
bevy-persistent = { workspace = true }
unprofile = { path = "../unprofile" }
unplayer = { path = "../unplayer" }
