[package]
name = "untmxmap-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
undifficulty-core = { workspace = true }
unboard-core = { workspace = true }

bevy = { workspace = true }
bevy_platform = { workspace = true }
tiled = { workspace = true }
unrender-std = { workspace = true }
thiserror = { workspace = true }
