[package]
name = "uncommon-app-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
rand = { workspace = true }
bevy_platform = { workspace = true }
