[package]
name = "unmanual"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
uncore-types = { path = "../uncore-types" }
uncore-resources = { path = "../uncore-resources" }
uncore-foundation = { path = "../uncore-foundation" }
uncore-events = { path = "../uncore-events" }
undifficulty = { path = "../undifficulty" }
bevy = { workspace = true }
bevy_platform = { workspace = true }
