[package]
name = "walkie_voice_generator"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
unwalkie-types = { path = "../../../unwalkie-types" }
clap = { workspace = true }
serde = { workspace = true }
ron = { workspace = true }
sha2 = { workspace = true }
walkdir = { workspace = true }
anyhow = { workspace = true }
rayon = { workspace = true }
