# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "ungame"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]

unspatial = { path = "../unspatial" }
uncore-assets = { path = "../uncore-assets" }
undifficulty = { path = "../undifficulty" }
uncore-foundation = { path = "../uncore-foundation" }
uncore-board = { path = "../uncore-board" }
uncore-events = { path = "../uncore-events" }
uncore-types = { path = "../uncore-types" }
uncore-resources = { path = "../uncore-resources" }
unui = { path = "../unui" }
untags = { path = "../untags" }
unrender = { path = "../unrender" }
unplayer-core = { path = "../unplayer-core" }
unpicking = { path = "../unpicking" }
uninteraction = { path = "../uninteraction" }
ungear = { path = "../ungear" }
unsettings = { path = "../unsettings" }
unlight = { path = "../unlight" }
unprofile = { path = "../unprofile" }
unplayer = { path = "../unplayer" }
unghost = { path = "../unghost" }
unghost-core = { path = "../unghost-core" }
uncore-components = { path = "../uncore-components" }

bevy = { workspace = true }
bevy_platform = { workspace = true }
bevy-persistent = { workspace = true }
