[package]
name = "unsummary-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[dependencies]
bevy = { workspace = true }
unfoundation-core = { path = "../unfoundation-core" }
undifficulty-core = { path = "../undifficulty-core" }
