[package]
name = "unsummary-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
bevy-persistent = { workspace = true }

undifficulty-core = { path = "../undifficulty-core" }
unassets-core = { path = "../unassets-core" }
unfoundation-core = { path = "../unfoundation-core" }
unboard-core = { path = "../unboard-core" }
untypes-core = { path = "../untypes-core" }
unsummary-core = { path = "../unsummary-core" }
unui-core = { path = "../unui-core" }
unprofile-core = { path = "../unprofile-core" }
unplayer-core = { path = "../unplayer-core" }
unghost-core = { path = "../unghost-core" }
