[package]
name = "unsummary-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }

undifficulty-core = { workspace = true }
untmxmap-core = { workspace = true }
unfoundation-core = { workspace = true }
unboard-core = { workspace = true }
untypes-core = { workspace = true }
uncareer-core = { workspace = true }
unmission-core = { workspace = true }

unui-core = { workspace = true }
unplayer-core = { workspace = true }
unghost-core = { workspace = true }
unvitals-core = { workspace = true }
unreplicon-core = { workspace = true }
