[package]
name = "ungear-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]

unspatial-core = { path = "../unspatial-core" }
unfoundation-core = { path = "../unfoundation-core" }
unevents-core = { path = "../unevents-core" }
unplayer-core = { path = "../unplayer-core" }
unghost-core = { path = "../unghost-core" }

bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
bevy_platform = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
enum-iterator = { workspace = true }
