[package]
name = "ungear-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]

unspatial-core = { path = "../unspatial-core" }
unfoundation-core = { path = "../unfoundation-core" }
unevents-core = { path = "../unevents-core" }
unplayer-core = { path = "../unplayer-core" }
unsettings-core = { path = "../unsettings-core" }
unprofile-core = { path = "../unprofile-core" }

bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
bevy_platform = { workspace = true }
bevy-persistent = { workspace = true }
