[package]
name = "unrender"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bevy = { workspace = true }
serde = { workspace = true }
uncore-types = { path = "../uncore-types" }
unspatial = { path = "../unspatial" }
uncore-board = { path = "../uncore-board" }
uncore-resources = { path = "../uncore-resources" }
unmetrics = { path = "../unmetrics" }
untags = { path = "../untags" }
bevy_platform = { workspace = true }
