[package]
name = "unroot-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unassets-core = { path = "../unassets-core" }
undifficulty-core = { path = "../undifficulty-core" }
untypes-core = { path = "../untypes-core" }
unevents-core = { path = "../unevents-core" }
unmenu-core = { path = "../unmenu-core" }
unghost-core = { path = "../unghost-core" }
unplayer-core = { path = "../unplayer-core" }
unnoise-core = { path = "../unnoise-core" }
unui-plugin = { path = "../unui-plugin" }
bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
