const UNHAUNTER_CRATES: &[&str] = &[
    "unhaunter",
    "unaudiobg_core",
    "unaudiobg_plugin",
    "unaudiospatial_core",
    "unaudiospatial_plugin",
    "unbehavior",
    "unbehavior_core",
    "unboard_core",
    "unboard_plugin",
    "uncampaign_plugin",
    "uncareer_core",
    "uncareer_plugin",
    "unclassic_mode_core",
    "unclassic_mode_gameplay_plugin",
    "unclassic_mode_orchestrator_plugin",
    "unclassic_mode_render_plugin",
    "unclassic_mode_ui_plugin",
    "uncommon_app_core",
    "undifficulty_core",
    "undifficulty_plugin",
    "unfog_core",
    "unfog_plugin",
    "unfps_plugin",
    "ungear_core",
    "ungear_plugin",
    "ungearitems_core",
    "ungearitems_plugin",
    "unghost_core",
    "unghost_plugin",
    "unhub_client",
    "unhub_plugin",
    "uninput_core",
    "uninput_plugin",
    "uninteraction_core",
    "uninteraction_plugin",
    "uninventory_plugin",
    "uninvestigation_core",
    "unlight_core",
    "unlight_plugin",
    "unlobby_core",
    "unlobby_plugin",
    "unlocomotion_core",
    "unlocomotion_plugin",
    "unmainmenu_plugin",
    "unmanual_core",
    "unmanual_plugin",
    "unmaphub_core",
    "unmaphub_plugin",
    "unmapload_core",
    "unmapload_plugin",
    "unmenu_core",
    "unmenu_plugin",
    "unmenusettings_plugin",
    "unmetrics_core",
    "unmetrics_plugin",
    "unmission_core",
    "unmission_plugin",
    "unnavigation_core",
    "unnavigation_plugin",
    "unnoise_core",
    "unnpc_core",
    "unnpc_plugin",
    "unorchestrator_core",
    "unpause_plugin",
    "unpicking_core",
    "unpicking_plugin",
    "unplayer_core",
    "unplayer_plugin",
    "unprofile_core",
    "unprofile_plugin",
    "unrender_plugin",
    "unrender_std",
    "unreplicon_core",
    "unreplicon_plugin",
    "unreplicon_transport",
    "unsettings_core",
    "unsettings_plugin",
    "unsoundfield_core",
    "unsoundfield_plugin",
    "unspatial_core",
    "unspatial_plugin",
    "unsummary_plugin",
    "unthermal_core",
    "unthermal_plugin",
    "untiled_core",
    "untmxmap_core",
    "untmxmap_plugin",
    "untruck_core",
    "untruck_plugin",
    "untruckui_plugin",
    "unvitals_core",
    "unvitals_plugin",
    "unwalkie_core",
    "unwalkie_plugin",
    "unwalkie_types",
];

/// Third-party networking crates that are worth watching when debugging multiplayer.
/// Capped at `debug` because their `trace` output is extremely high-volume.
const NETWORKING_CRATES: &[&str] = &[
    "bevy_replicon",
    "bevy_replicon_renet",
    "bevy_renet",
    "renet",
    "renet_netcode",
];

pub fn build_log_filter(verbose: u8) -> String {
    let level = match verbose {
        0 => "warn",
        1 => "info",
        2 => "debug",
        _ => "trace",
    };
    // Networking crates are capped at debug — their trace output is extremely noisy.
    let net_level = match verbose {
        0 => "warn",
        1 => "warn",
        2 => "info",
        3 => "info",
        _ => "debug",
    };
    let mut filter = "warn,wgpu_hal=error".to_string();
    for c in UNHAUNTER_CRATES {
        filter.push_str(&format!(",{}={}", c, level));
    }
    for c in NETWORKING_CRATES {
        filter.push_str(&format!(",{}={}", c, net_level));
    }
    filter.push_str(",bevy_replicon::shared::message::client_message=warn");
    filter
}
