[package]
name = "unwalkie-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
unwalkie-types = { workspace = true }

uncommon-app-core = { workspace = true }
uninvestigation-core = { workspace = true }
undifficulty-core = { workspace = true }
ungear-core = { workspace = true }

bevy = { workspace = true }
bevy_platform = { workspace = true }
enum-iterator = { workspace = true }
rand = { workspace = true }
