[package]
name = "unwalkie-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[dependencies]
unwalkie-types = { path = "../unwalkie-types" }

uncore-foundation = { path = "../uncore-foundation" }
uncore-types = { path = "../uncore-types" }
ungear = { path = "../ungear" }

bevy = { workspace = true }
bevy_platform = { workspace = true }
enum-iterator = { workspace = true }
rand = { workspace = true }
