[package]
name = "ungear"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]

unspatial = { path = "../unspatial" }
undifficulty = { path = "../undifficulty" }
uncore-foundation = { path = "../uncore-foundation" }
uncore-events = { path = "../uncore-events" }
uncore-types = { path = "../uncore-types" }
uncore-resources = { path = "../uncore-resources" }
uncore-components = { path = "../uncore-components" }
unsettings = { path = "../unsettings" }
unprofile = { path = "../unprofile" }
untags = { path = "../untags" }
unghost-core = { path = "../unghost-core" }

bevy = { workspace = true }
bevy-persistent = { workspace = true }
