[package]
name = "ungear"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]

undifficulty = { path = "../undifficulty" }
uncore-foundation = { path = "../uncore-foundation" }
uncore-board = { path = "../uncore-board" }
uncore-assets = { path = "../uncore-assets" }
uncore-events = { path = "../uncore-events" }
uncore-types = { path = "../uncore-types" }
uncore-resources = { path = "../uncore-resources" }
uncore-components = { path = "../uncore-components" }
uncore-systems = { path = "../uncore-systems" }
unsettings = { path = "../unsettings" }
unprofile = { path = "../unprofile" }

bevy = { workspace = true }
serde = { workspace = true }
enum-iterator = { workspace = true }
thiserror = { workspace = true }
fastapprox = { workspace = true }
rand = { workspace = true }
bevy-persistent = { workspace = true }
