[package]
name = "unroot"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
uncore-resources = { path = "../uncore-resources" }
uncore-types = { path = "../uncore-types" }
bevy = { workspace = true }
bevy_framepace = { workspace = true }
