[package]
name = "ungear-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ungear-core = { path = "../ungear-core" }
unrender-std = { path = "../unrender-std" }
unspatial-core = { path = "../unspatial-core" }
unfoundation-core = { path = "../unfoundation-core" }
untypes-core = { path = "../untypes-core" }
unboard-core = { path = "../unboard-core" }
unplayer-core = { path = "../unplayer-core" }
unsettings-core = { path = "../unsettings-core" }
untags-core = { path = "../untags-core" }
untruck-core = { path = "../untruck-core" }
unmetrics-core = { path = "../unmetrics-core" }

bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
bevy-persistent = { workspace = true }
