[package]
name = "ungear-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ungear-core = { path = "../ungear-core" }
unrender-std = { path = "../unrender-std" }
unspatial-core = { path = "../unspatial-core" }
unassets-core = { path = "../unassets-core" }
undifficulty-core = { path = "../undifficulty-core" }
unfoundation-core = { path = "../unfoundation-core" }
unevents-core = { path = "../unevents-core" }
untypes-core = { path = "../untypes-core" }
unsummary-core = { path = "../unsummary-core" }
uninteraction-core = { path = "../uninteraction-core" }
unboard-core = { path = "../unboard-core" }
unplayer-core = { path = "../unplayer-core" }
unsettings-core = { path = "../unsettings-core" }
unprofile-core = { path = "../unprofile-core" }
untags-core = { path = "../untags-core" }
unghost-core = { path = "../unghost-core" }

bevy = { workspace = true }
bevy_platform = { workspace = true }
bevy-persistent = { workspace = true }
