[package]
name = "uncampaign-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[dependencies]

undifficulty-core = { path = "../undifficulty-core" }
uncore-foundation = { path = "../uncore-foundation" }
uncore-assets = { path = "../uncore-assets" }
uncore-events = { path = "../uncore-events" }
uncore-types = { path = "../uncore-types" }
unmenu-core = { path = "../unmenu-core" }
unprofile-core = { path = "../unprofile-core" }

bevy = { workspace = true }
bevy-persistent = { workspace = true }
