[package]
name = "uncampaign-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]

undifficulty-core = { path = "../undifficulty-core" }
unfoundation-core = { path = "../unfoundation-core" }
unui-core = { path = "../unui-core" }
unassets-core = { path = "../unassets-core" }
unevents-core = { path = "../unevents-core" }
untypes-core = { path = "../untypes-core" }
unmenu-core = { path = "../unmenu-core" }
unprofile-core = { path = "../unprofile-core" }

bevy = { workspace = true }
bevy-persistent = { workspace = true }
