[package]
name = "uncore-assets"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
uncore-types = { path = "../uncore-types" }
bevy = { workspace = true }
bevy_platform = { workspace = true }
thiserror = { workspace = true }
