[package]
name = "unghost"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]

undifficulty = { path = "../undifficulty" }
uncore-foundation = { path = "../uncore-foundation" }
uncore-board = { path = "../uncore-board" }
uncore-events = { path = "../uncore-events" }
uncore-resources = { path = "../uncore-resources" }
unrender = { path = "../unrender" }
unplayer-core = { path = "../unplayer-core" }
unmetrics = { path = "../unmetrics" }
unnoise = { path = "../unnoise" }
uninteraction = { path = "../uninteraction" }
ungear = { path = "../ungear" }
ungearitems = { path = "../ungearitems" }
untags = { path = "../untags" }
unspatial = { path = "../unspatial" }
unghost-core = { path = "../unghost-core" }

bevy = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
