[package]
name = "unghost"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]

undifficulty = { path = "../undifficulty" }
uncore-foundation = { path = "../uncore-foundation" }
uncore-board = { path = "../uncore-board" }
uncore-events = { path = "../uncore-events" }
uncore-resources = { path = "../uncore-resources" }
uncore-components = { path = "../uncore-components" }
uncore-systems = { path = "../uncore-systems" }
unstd = { path = "../unstd" }
ungear = { path = "../ungear" }
ungearitems = { path = "../ungearitems" }

bevy = { workspace = true }
rand = { workspace = true }
ordered-float = { workspace = true }
