[package]
name = "unmenu-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]

unui-core = { path = "../unui-core" }
unfoundation-core = { path = "../unfoundation-core" }
untypes-core = { path = "../untypes-core" }
unprofile-core = { path = "../unprofile-core" }

bevy = { workspace = true }
