[package]
name = "unbehavior-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unspatial-core = { workspace = true }
bevy = { workspace = true }
bevy_platform = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
fastapprox = { workspace = true }
