[package]
name = "unvitals-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
unplayer-core = { workspace = true }
untypes-core = { workspace = true }
unsoundfield-core = { workspace = true }
unsummary-core = { workspace = true }
undifficulty-core = { workspace = true }
unspatial-core = { workspace = true }
unreplicon-core = { workspace = true }
unghost-core = { workspace = true }
untags-core = { workspace = true }
unlight-core = { workspace = true }
unui-core = { workspace = true }
unboard-core = { workspace = true }
unthermal-core = { workspace = true }
untruck-core = { workspace = true }
unprofile-core = { workspace = true }
bevy-persistent = { workspace = true }
