# .github/workflows/deploy-zola-site.yml (Modified - Stage 1: Include WASM)
name: Deploy Zola Website with WASM to GitHub Pages

on:
  push:
    branches:
      - website
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website branch
        uses: actions/checkout@v4
        # No 'ref' needed, defaults to 'website'

      - name: Set up Rust (for Zola)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Zola CLI
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1

      # === NEW WASM GAME FETCHING STEPS ===
      - name: Create WASM Output Directory
        run: mkdir -p static/wasm/main/pkg

      - name: Get Latest Stable Release Tag
        id: latest_release
        run: |
          # Get the latest release tag (excluding pre-releases)
          LATEST_TAG=$(gh release list --limit 1 --exclude-pre-releases --json tagName --jq '.[0].tagName' || echo "none")
          echo "Latest Release Tag: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Latest Stable WASM Game
        if: steps.latest_release.outputs.LATEST_TAG != 'none' && steps.latest_release.outputs.LATEST_TAG != 'null'
        run: |
          gh release download "${{ steps.latest_release.outputs.LATEST_TAG }}" --pattern "unhaunter-*wasm.zip" -O latest-wasm-release.zip
          unzip latest-wasm-release.zip -d wasm-release-temp
          # Assuming wasm-pack puts the WASM files in a 'pkg' directory inside the zip
          cp -r wasm-release-temp/pkg/* static/wasm/main/pkg/
          echo "Latest stable WASM game downloaded and extracted to static/wasm/main/pkg"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup temp WASM download
        if: steps.latest_release.outputs.LATEST_TAG != 'none' && steps.latest_release.outputs.LATEST_TAG != 'null'
        run: rm -rf wasm-release-temp latest-wasm-release.zip

      - name: Build Zola site
        run: zola build
        # Zola will now include the WASM game from static/wasm/main/pkg

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public # Upload 'public' directory

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
