[package]
name = "uncore-components"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
uncore-foundation = { path = "../uncore-foundation" }
uncore-board = { path = "../uncore-board" }
uncore-types = { path = "../uncore-types" }
uncore-events = { path = "../uncore-events" }
bevy = { workspace = true }
rand = { workspace = true }
bevy_picking = { workspace = true }
serde = { workspace = true }
fastapprox = { workspace = true }
unsettings = { path = "../unsettings" }
