[package]
name = "unlight"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]

unspatial = { path = "../unspatial" }
undifficulty = { path = "../undifficulty" }
uncore-foundation = { path = "../uncore-foundation" }
uncore-board = { path = "../uncore-board" }
uncore-events = { path = "../uncore-events" }
uncore-types = { path = "../uncore-types" }
uncore-resources = { path = "../uncore-resources" }
unrender = { path = "../unrender" }
unplayer-core = { path = "../unplayer-core" }
unmetrics = { path = "../unmetrics" }
unfog = { path = "../unfog" }
ungear = { path = "../ungear" }
ungearitems = { path = "../ungearitems" }
unsettings = { path = "../unsettings" }
unghost = { path = "../unghost" }
unghost-core = { path = "../unghost-core" }

bevy = { workspace = true }
bevy_platform = { workspace = true }
rand = { workspace = true }
ndarray = { workspace = true }
fastapprox = { workspace = true }
bevy-persistent = { workspace = true }
