[package]
name = "unclassic-mode-orchestrator-plugin"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unbehavior-core = { workspace = true }
unboard-core = { workspace = true }
undifficulty-core = { workspace = true }
unfoundation-core = { workspace = true }
unghost-core = { workspace = true }
unlight-core = { workspace = true }
unsensing-core = { workspace = true }
unmapload-core = { workspace = true }
unmission-core = { workspace = true }
unplayer-core = { workspace = true }
unrender-std = { workspace = true }
unreplicon-core = { workspace = true }
unspatial-core = { workspace = true }
unsoundfield-core = { workspace = true }
unsummary-core = { workspace = true }
untags-core = { workspace = true }
untypes-core = { workspace = true }
bevy = { workspace = true }
bevy_platform = { workspace = true }
ordered-float = { workspace = true }
rand = { workspace = true }
