[package]
name = "unmission-plugin"
version.workspace = true
edition.workspace = true
description = "Mission lifecycle logic for Unhaunter"
repository.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
unboard-core = { path = "../unboard-core" }
unmission-core = { path = "../unmission-core" }
untypes-core = { path = "../untypes-core" }
unsummary-core = { path = "../unsummary-core" }
unprofile-core = { path = "../unprofile-core" }
unplayer-core = { path = "../unplayer-core" }
unreplicon-core = { workspace = true }
untruck-core = { path = "../untruck-core" }
unspatial-core = { path = "../unspatial-core" }

bevy = { workspace = true }
bevy-persistent = { workspace = true }
